
package gameenumeration.unit;

import java.util.ArrayList;
import java.util.List;

public class UnitType {
   
   private static final String NO_ICON = "building university icons 64.bmp";
   
   private static final UnitType INSTANCE = new UnitType();
   
   public static UnitType getInstance() {
      return INSTANCE;
   }
   
   private List<UnitEntry> units;
   
   private UnitType() {
      units = new ArrayList<>();
      units.add(new UnitEntry(0, "Hawk", "Hawk", "world hawk icon 64.bmp"));
      units.add(new UnitEntry(1, "Palm Stump", "Palm Stump", NO_ICON));
      units.add(new UnitEntry(2, "Bush", "Bush", NO_ICON));
      units.add(new UnitEntry(3, "Arrow", "Arrow", NO_ICON));
      units.add(new UnitEntry(4, "Axe", "Axe", NO_ICON));
      units.add(new UnitEntry(5, "Blood", "Blood", NO_ICON));
      units.add(new UnitEntry(6, "Scarab Blood", "Scarab Blood", NO_ICON));
      units.add(new UnitEntry(7, "Waypoint Flag", "Waypoint Flag", NO_ICON));
      units.add(new UnitEntry(8, "Moveto", "Moveto", NO_ICON));
      units.add(new UnitEntry(9, "Test Object", "Test Object", NO_ICON));
      units.add(new UnitEntry(10, "Yardstick", "Yardstick", NO_ICON));
      units.add(new UnitEntry(11, "Smoke", "Smoke", NO_ICON));
      units.add(new UnitEntry(12, "Cloud", "Cloud", NO_ICON));
      units.add(new UnitEntry(13, "Tornado", "Tornado", NO_ICON));
      units.add(new UnitEntry(14, "Revealer", "Revealer", NO_ICON));
      units.add(new UnitEntry(15, "Attack Revealer", "Attack Revealer", NO_ICON));
      units.add(new UnitEntry(16, "Construction Small", "Construction Small", NO_ICON));
      units.add(new UnitEntry(17, "Construction Medium", "Construction Medium", NO_ICON));
      units.add(new UnitEntry(18, "Construction Large", "Construction Large", NO_ICON));
      units.add(new UnitEntry(19, "Construction Extra Large", "Construction Extra Large", NO_ICON));
      units.add(new UnitEntry(20, "Ice Block", "Ice Block", NO_ICON));
      units.add(new UnitEntry(21, "Papyrus", "Papyrus", NO_ICON));
      units.add(new UnitEntry(22, "Wave", "Wave", NO_ICON));
      units.add(new UnitEntry(23, "Rainfall", "Rainfall", NO_ICON));
      units.add(new UnitEntry(24, "Ice Sheet", "Ice Sheet", NO_ICON));
      units.add(new UnitEntry(25, "Camera", "Camera", NO_ICON));
      units.add(new UnitEntry(26, "Camera Motion Arrow", "Camera Motion Arrow", NO_ICON));
      units.add(new UnitEntry(27, "Camera Start", "Camera Start", NO_ICON));
      units.add(new UnitEntry(28, "Whale", "Whale", NO_ICON));
      units.add(new UnitEntry(29, "Fire Pit", "Fire Pit", NO_ICON));
      units.add(new UnitEntry(30, "Rock Symbols", "Rock Symbols", NO_ICON));
      units.add(new UnitEntry(31, "Stalagmite", "Stalagmite", NO_ICON));
      units.add(new UnitEntry(32, "Runestone", "Runestone", NO_ICON));
      units.add(new UnitEntry(33, "Rock Snow", "Rock Snow", NO_ICON));
      units.add(new UnitEntry(34, "Water Lilly", "Water Lily", NO_ICON));
      units.add(new UnitEntry(35, "Water Reeds", "Water Reeds", NO_ICON));
      units.add(new UnitEntry(36, "Snowfall", "Snowfall", NO_ICON));
      units.add(new UnitEntry(37, "Mist", "Mist", NO_ICON));
      units.add(new UnitEntry(38, "Waterfall", "Waterfall", NO_ICON));
      units.add(new UnitEntry(39, "Garrison Flag", "Garrison Flag", NO_ICON));
      units.add(new UnitEntry(40, "Crate", "Crate", NO_ICON));
      units.add(new UnitEntry(41, "Rugs", "Rugs", NO_ICON));
      units.add(new UnitEntry(42, "Market Stall", "Market Stall", "icon building market.bmp"));
      units.add(new UnitEntry(43, "Catapult Shot", "Catapult Shot", NO_ICON));
      units.add(new UnitEntry(44, "Misc Objects", "Misc Objects", NO_ICON));
      units.add(new UnitEntry(45, "Inferno Fire Ground", "Inferno Fire Ground", NO_ICON));
      units.add(new UnitEntry(46, "Lightning Strike", "Lightning Strike", NO_ICON));
      units.add(new UnitEntry(47, "Ballista Shot", "Ballista Shot", NO_ICON));
      units.add(new UnitEntry(48, "Splash", "Splash", NO_ICON));
      units.add(new UnitEntry(49, "Misc Stairs", "Misc Stairs", NO_ICON));
      units.add(new UnitEntry(50, "Coral Reef", "Coral Reef", NO_ICON));
      units.add(new UnitEntry(51, "Hero Birth", "Hero Birth", NO_ICON));
      units.add(new UnitEntry(52, "Cinematic Block", "Cinematic Block", NO_ICON));
      units.add(new UnitEntry(53, "Footprint Villager", "Footprint Villager", NO_ICON));
      units.add(new UnitEntry(54, "Flaming Footprint", "Flaming Footprint", NO_ICON));
      units.add(new UnitEntry(55, "Icy Footprint", "Icy Footprint", NO_ICON));
      units.add(new UnitEntry(56, "Oar Footprint", "Oar Footprint", NO_ICON));
      units.add(new UnitEntry(57, "Meteor", "Meteor", NO_ICON));
      units.add(new UnitEntry(58, "Lightning sparks", "Lightning sparks", NO_ICON));
      units.add(new UnitEntry(59, "Lightning Scorch", "Lightning Scorch", NO_ICON));
      units.add(new UnitEntry(60, "Dust Small", "Dust Small", NO_ICON));
      units.add(new UnitEntry(61, "Dust Medium", "Dust Medium", NO_ICON));
      units.add(new UnitEntry(62, "Dust Large", "Dust Large", NO_ICON));
      units.add(new UnitEntry(63, "Arrow Flaming", "Arrow Flaming", NO_ICON));
      units.add(new UnitEntry(64, "Lightning Cloud", "Lightning Cloud", NO_ICON));
      units.add(new UnitEntry(65, "Lightning Rain", "Lightning Rain", NO_ICON));
      units.add(new UnitEntry(66, "UI Army Banner Furled", "UI Army Banner Furled", NO_ICON));
      units.add(new UnitEntry(67, "UI Army Banner Plain", "UI Army Banner Plain", NO_ICON));
      units.add(new UnitEntry(68, "UI Army Banner Infantry", "UI Army Banner Infantry", NO_ICON));
      units.add(new UnitEntry(69, "UI Army Banner Cavalry", "UI Army Banner Cavalry", NO_ICON));
      units.add(new UnitEntry(70, "UI Army Banner Archer", "UI Army Banner Archer", NO_ICON));
      units.add(new UnitEntry(71, "UI Army Banner Villager", "UI Army Banner Villager", NO_ICON));
      units.add(new UnitEntry(72, "Blood Gore", "Blood Gore", NO_ICON));
      units.add(new UnitEntry(73, "Lightning Sparks Ground", "Lightning Sparks Ground", NO_ICON));
      units.add(new UnitEntry(74, "Hoofprint", "Hoofprint", NO_ICON));
      units.add(new UnitEntry(75, "Footprint Military", "Footprint Military", NO_ICON));
      units.add(new UnitEntry(76, "Fire Object", "Fire", NO_ICON));
      units.add(new UnitEntry(77, "UI Hero Banner", "UI Hero Banner", NO_ICON));
      units.add(new UnitEntry(78, "UI Idle Villager Banner", "UI Idle Villager Banner", NO_ICON));
      units.add(new UnitEntry(79, "Giant Footprint", "Giant Footprint", NO_ICON));
      units.add(new UnitEntry(80, "Shark", "Shark", NO_ICON));
      units.add(new UnitEntry(81, "Orca", "Orca", NO_ICON));
      units.add(new UnitEntry(82, "Rock Granite Small", "Rock Granite Small", NO_ICON));
      units.add(new UnitEntry(83, "Rock Limestone Small", "Rock Limestone Small", NO_ICON));
      units.add(new UnitEntry(84, "Grass", "Grass", NO_ICON));
      units.add(new UnitEntry(85, "Seagull", "Seagull", NO_ICON));
      units.add(new UnitEntry(86, "Rock Granite Big", "Rock Granite Big", NO_ICON));
      units.add(new UnitEntry(87, "Rock Limestone Big", "Rock Limestone Big", NO_ICON));
      units.add(new UnitEntry(88, "Rock Sandstone Big", "Rock Sandstone Big", NO_ICON));
      units.add(new UnitEntry(89, "Rock Sandstone Small", "Rock Sandstone Small", NO_ICON));
      units.add(new UnitEntry(90, "Rock River Sandy", "Rock River Sandy", NO_ICON));
      units.add(new UnitEntry(91, "Rock River Grassy", "Rock River Grassy", NO_ICON));
      units.add(new UnitEntry(92, "Rock River Icy", "Rock River Icy", NO_ICON));
      units.add(new UnitEntry(93, "Shifting Sands In", "Shifting Sands In", NO_ICON));
      units.add(new UnitEntry(94, "UI Army Banner Myth", "UI Army Banner Myth", NO_ICON));
      units.add(new UnitEntry(95, "UI Idle Military Banner", "UI Idle Military Banner", NO_ICON));
      units.add(new UnitEntry(96, "Heavenlight", "Heavenlight", NO_ICON));
      units.add(new UnitEntry(97, "Shifting Sands Out", "Shifting Sands Out", NO_ICON));
      units.add(new UnitEntry(98, "Shifting Sands Out Effect", "Shifting Sands Out Effect", NO_ICON));
      units.add(new UnitEntry(99, "Inferno Unit Flame", "Inferno Unit Flame", NO_ICON));
      units.add(new UnitEntry(100, "Revealer to Player", "Revealer to Player", NO_ICON));
      units.add(new UnitEntry(101, "Skeleton", "Skeleton", NO_ICON));
      units.add(new UnitEntry(102, "Sand Drift Dune", "Sand Drift Dune", NO_ICON));
      units.add(new UnitEntry(103, "Sand Drift Plain", "Sand Drift Plain", NO_ICON));
      units.add(new UnitEntry(104, "Sand Drift Patch", "Sand Drift Patch", NO_ICON));
      units.add(new UnitEntry(105, "Healing SFX", "Healing SFX", NO_ICON));
      units.add(new UnitEntry(106, "Healing Area SFX", "Healing Area SFX", NO_ICON));
      units.add(new UnitEntry(107, "Frost Drift", "Frost Drift", NO_ICON));
      units.add(new UnitEntry(108, "Dust Devil", "Dust Devil", NO_ICON));
      units.add(new UnitEntry(109, "Fountain", "Fountain", "icon object fountain 64.bmp"));
      units.add(new UnitEntry(110, "Fire Wood", "Fire Wood", "wood 64.bmp"));
      units.add(new UnitEntry(111, "Campfire", "Campfire", NO_ICON));
      units.add(new UnitEntry(112, "Columns", "Columns", "world column icon 64.bmp"));
      units.add(new UnitEntry(113, "Columns Fallen", "Fallen Columns", "world column icon 64.bmp"));
      units.add(new UnitEntry(114, "Columns Broken", "Broken Columns", "world column icon 64.bmp"));
      units.add(new UnitEntry(115, "Milestone", "Milestone", NO_ICON));
      units.add(new UnitEntry(116, "Sign", "Sign", "scenario sign icon 64.bmp"));
      units.add(new UnitEntry(117, "Clone SFX", "Clone SFX", NO_ICON));
      units.add(new UnitEntry(118, "Invisible Ram", "Invisible Ram", NO_ICON));
      units.add(new UnitEntry(119, "Spear", "Spear", NO_ICON));
      units.add(new UnitEntry(120, "Sling Stone", "Sling Stone", NO_ICON));
      units.add(new UnitEntry(121, "Rain", "Rain", NO_ICON));
      units.add(new UnitEntry(122, "Snow Storm", "Snow Storm", NO_ICON));
      units.add(new UnitEntry(123, "Fertile Plants SFX", "Fertile Plants SFX", NO_ICON));
      units.add(new UnitEntry(124, "Cinematic rocks", "Cinematic rocks", NO_ICON));
      units.add(new UnitEntry(125, "Cinematic Trees", "Cinematic Trees", "icon pine tree.bmp"));
      units.add(new UnitEntry(126, "Cinematic Dead Bodies", "Cinematic Dead Bodies", NO_ICON));
      units.add(new UnitEntry(127, "Destroyed Buildings Small", "Destroyed Building", NO_ICON));
      units.add(new UnitEntry(128, "Cinematic Scorch", "Cinematic Scorch", NO_ICON));
      units.add(new UnitEntry(129, "undermine ground decal long", "undermine ground decal long", NO_ICON));
      units.add(new UnitEntry(130, "undermine ground decal short", "undermine ground decal short", NO_ICON));
      units.add(new UnitEntry(131, "undermine ground decal corner", "undermine ground decal corner", NO_ICON));
      units.add(new UnitEntry(132, "Armor Glow Small", "Armor Glow Small", NO_ICON));
      units.add(new UnitEntry(133, "Tornado Debris", "Tornado Debris", NO_ICON));
      units.add(new UnitEntry(134, "Raft", "Raft", "boat e transport icon.bmp"));
      units.add(new UnitEntry(135, "Meteor Impact Water", "Meteor Impact Water", NO_ICON));
      units.add(new UnitEntry(136, "Meteor Impact Ground", "Meteor Impact Ground", NO_ICON));
      units.add(new UnitEntry(137, "Rain Small", "Rain Small", NO_ICON));
      units.add(new UnitEntry(138, "Ball of Fire", "Ball of Fire", NO_ICON));
      units.add(new UnitEntry(139, "Increase Prosperity Large", "Increase Prosperity Large", NO_ICON));
      units.add(new UnitEntry(140, "Increase Prosperity Small", "Increase Prosperity Small", NO_ICON));
      units.add(new UnitEntry(141, "Ball of fire impact", "Ball of fire impact", NO_ICON));
      units.add(new UnitEntry(142, "Dove", "Dove", NO_ICON));
      units.add(new UnitEntry(143, "Snow Drift Archery", "Snow Drift Archery", NO_ICON));
      units.add(new UnitEntry(144, "Snow Drift Barracks", "Snow Drift Barracks", NO_ICON));
      units.add(new UnitEntry(145, "Snow Drift Stable", "Snow Drift Stable", NO_ICON));
      units.add(new UnitEntry(146, "Snow Drift Settlements", "Snow Drift Settlements", NO_ICON));
      units.add(new UnitEntry(147, "Snow Drift Tower", "Snow Drift Tower", NO_ICON));
      units.add(new UnitEntry(148, "Snow Drift Siege", "Snow Drift Siege", NO_ICON));
      units.add(new UnitEntry(149, "Snow Drift Major Temple", "Snow Drift Major Temple", NO_ICON));
      units.add(new UnitEntry(150, "Tunnel Opening", "Tunnel Opening", "god power underworld passage icon.bmp"));
      units.add(new UnitEntry(151, "Volley", "Volley", NO_ICON));
      units.add(new UnitEntry(152, "Hades Fire", "Hades Fire", NO_ICON));
      units.add(new UnitEntry(153, "Rock Granite Sprite", "Rock Granite Sprite", NO_ICON));
      units.add(new UnitEntry(154, "Vision Revealer", "Vision Revealer", NO_ICON));
      units.add(new UnitEntry(155, "Bolt Strike", "Bolt Strike", NO_ICON));
      units.add(new UnitEntry(156, "Spy Eye", "Spy Eye", NO_ICON));
      units.add(new UnitEntry(157, "Curse SFX", "Curse SFX", NO_ICON));
      units.add(new UnitEntry(158, "Sentinel Base", "Sentinel Base", "god power sentinel icon.bmp"));
      units.add(new UnitEntry(159, "Bolt Scorch", "Bolt Scorch", NO_ICON));
      units.add(new UnitEntry(160, "Citadel SFX", "Citadel SFX", NO_ICON));
      units.add(new UnitEntry(161, "Vision SFX", "Vision SFX", NO_ICON));
      units.add(new UnitEntry(162, "Ragnorok SFX", "Ragnarok SFX", NO_ICON));
      units.add(new UnitEntry(163, "Fimbulwinter SFX", "Fimbulwinter SFX", NO_ICON));
      units.add(new UnitEntry(164, "Plenty Flare", "Plenty Flare", NO_ICON));
      units.add(new UnitEntry(165, "Osiris Lightning", "Osiris Lightning", NO_ICON));
      units.add(new UnitEntry(166, "Osiris SFX", "Osiris SFX", NO_ICON));
      units.add(new UnitEntry(167, "Priest Projectile", "Priest Projectile", NO_ICON));
      units.add(new UnitEntry(168, "UI Army Banner Siege", "UI Army Banner Siege", NO_ICON));
      units.add(new UnitEntry(169, "Rock Limestone Sprite", "Rock Limestone Sprite", NO_ICON));
      units.add(new UnitEntry(170, "Rock Sandstone Sprite", "Rock Sandstone Sprite", NO_ICON));
      units.add(new UnitEntry(171, "Pine Stump", "Pine Stump", NO_ICON));
      units.add(new UnitEntry(172, "Oak stump", "Oak stump", NO_ICON));
      units.add(new UnitEntry(173, "Earthquake", "Earthquake", NO_ICON));
      units.add(new UnitEntry(174, "Barrel", "Barrel", NO_ICON));
      units.add(new UnitEntry(175, "Pots", "Pots", NO_ICON));
      units.add(new UnitEntry(176, "Broken Siege Weapons", "Broken Siege Weapons", NO_ICON));
      units.add(new UnitEntry(177, "Kraken Bits", "Kraken Bits", NO_ICON));
      units.add(new UnitEntry(178, "Flowers", "Flowers", NO_ICON));
      units.add(new UnitEntry(179, "Seaweed", "Seaweed", NO_ICON));
      units.add(new UnitEntry(180, "Fern", "Fern", NO_ICON));
      units.add(new UnitEntry(181, "Flag Numbered", "Flag Numbered", NO_ICON));
      units.add(new UnitEntry(182, "Scorpion Tail", "Scorpion Tail", NO_ICON));
      units.add(new UnitEntry(183, "Generic Corpse", "Generic Corpse", NO_ICON));
      units.add(new UnitEntry(184, "Wadjet Spit", "Wadjet Spit", NO_ICON));
      units.add(new UnitEntry(185, "Hero Death", "Hero Death", NO_ICON));
      units.add(new UnitEntry(186, "Petosuchus Beam", "Petsuchos Beam", NO_ICON));
      units.add(new UnitEntry(187, "Earthquake CrackA", "Earthquake CrackA", NO_ICON));
      units.add(new UnitEntry(188, "Earthquake CrackB", "Earthquake CrackB", NO_ICON));
      units.add(new UnitEntry(189, "Earthquake CrackC", "Earthquake CrackC", NO_ICON));
      units.add(new UnitEntry(190, "Earthquake CrackD", "Earthquake CrackD", NO_ICON));
      units.add(new UnitEntry(191, "Forest Fire SFX", "Forest Fire SFX", NO_ICON));
      units.add(new UnitEntry(192, "Petosuchus projectile", "Petsuchos projectile", NO_ICON));
      units.add(new UnitEntry(193, "Recognizer", "Recognizer", NO_ICON));
      units.add(new UnitEntry(194, "Manticore Barb", "Manticore Barb", NO_ICON));
      units.add(new UnitEntry(195, "Arrow Splash SFX", "Arrow Splash SFX", NO_ICON));
      units.add(new UnitEntry(196, "Petrobolos Shot", "Petrobolos Shot", NO_ICON));
      units.add(new UnitEntry(197, "UI Town Bell Banner", "UI Town Bell Banner", NO_ICON));
      units.add(new UnitEntry(198, "Pestilence SFX1", "Pestilence SFX1", NO_ICON));
      units.add(new UnitEntry(199, "Pestilence SFX2", "Pestilence SFX2", NO_ICON));
      units.add(new UnitEntry(200, "Hero Death Revealer", "Death Revealer", NO_ICON));
      units.add(new UnitEntry(201, "Testomatic", "Testomatic", NO_ICON));
      units.add(new UnitEntry(202, "Gate Ram Destroyed", "Giant Gate Ram", "special g hades ram icon 64.bmp"));
      units.add(new UnitEntry(203, "Spear Flaming", "Spear Flaming", NO_ICON));
      units.add(new UnitEntry(204, "Destroyed Buildings Med", "Destroyed Building", NO_ICON));
      units.add(new UnitEntry(205, "Destroyed Buildings Large", "Destroyed Building", NO_ICON));
      units.add(new UnitEntry(206, "Osiris", "Osiris", "improvement osiris icon.bmp"));
      units.add(new UnitEntry(207, "SPCMeteor", "SPCMeteor", NO_ICON));
      units.add(new UnitEntry(208, "Avalanche", "Avalanche", NO_ICON));
      units.add(new UnitEntry(209, "Einheriar Boost SFX", "Einheriar Boost SFX", NO_ICON));
      units.add(new UnitEntry(210, "Arrow Signal", "Arrow Flaming", NO_ICON));
      units.add(new UnitEntry(211, "Osiris Birth", "Osiris Birth", NO_ICON));
      units.add(new UnitEntry(212, "Osiris Box Glow", "Osiris Box Glow", NO_ICON));
      units.add(new UnitEntry(213, "UI Banner Objective", "UI Banner Objective", NO_ICON));
      units.add(new UnitEntry(214, "Oak stump burnt", "Oak stump burnt", NO_ICON));
      units.add(new UnitEntry(215, "Fire Object Big", "Fire", NO_ICON));
      units.add(new UnitEntry(216, "Smoke Big", "Smoke", NO_ICON));
      units.add(new UnitEntry(217, "UI Army Banner Hero", "UI Army Banner Hero", NO_ICON));
      units.add(new UnitEntry(218, "Mummy Flies", "Mummy Flies", NO_ICON));
      units.add(new UnitEntry(219, "Vulture", "Vulture", "special e vulture icon.bmp"));
      units.add(new UnitEntry(220, "Conversion SFX", "Conversion SFX", NO_ICON));
      units.add(new UnitEntry(221, "UI Army Banner Naval", "UI Army Banner Naval", NO_ICON));
      units.add(new UnitEntry(222, "Fire Hades", "Fire", NO_ICON));
      units.add(new UnitEntry(223, "Destruction 3x3", "Destruction 3x3", NO_ICON));
      units.add(new UnitEntry(224, "Destruction 4x4", "Destruction 4x4", NO_ICON));
      units.add(new UnitEntry(225, "Destruction 5x5", "Destruction 5x5", NO_ICON));
      units.add(new UnitEntry(226, "Destruction 8x8", "Destruction 8x8", NO_ICON));
      units.add(new UnitEntry(227, "Thor hammer", "The Hammer of Thor", NO_ICON));
      units.add(new UnitEntry(228, "Regeneration SFX", "Regeneration SFX", NO_ICON));
      units.add(new UnitEntry(229, "Poison SFX", "Poison SFX", NO_ICON));
      units.add(new UnitEntry(230, "Taproot large", "Taproot Trunk", "scenario taproot icon 64.bmp"));
      units.add(new UnitEntry(231, "Taproot Small", "Taproot Sprigg", "scenario taproot icon 64.bmp"));
      units.add(new UnitEntry(232, "Shadow", "Shadow", NO_ICON));
      units.add(new UnitEntry(233, "Destruction Settlement", "Destruction Settlement", NO_ICON));
      units.add(new UnitEntry(234, "Destruction 2x2", "Destruction 2x2", NO_ICON));
      units.add(new UnitEntry(235, "Destruction 1x1", "Destruction 1x1", NO_ICON));
      units.add(new UnitEntry(236, "UI Army Banner Caravan", "UI Army Banner Caravan", NO_ICON));
      units.add(new UnitEntry(237, "UI Army Banner Oxcart", "UI Army Banner Oxcart", NO_ICON));
      units.add(new UnitEntry(238, "MIne Pieces", "Mine Wall", NO_ICON));
      units.add(new UnitEntry(239, "Underworld Smoke", "Smoke Underworld", NO_ICON));
      units.add(new UnitEntry(240, "Underworld Explosion", "Underworld Explosion", NO_ICON));
      units.add(new UnitEntry(241, "UI Cloud Boarder", "UI Cloud Boarder", NO_ICON));
      units.add(new UnitEntry(242, "Blood Cinematic", "Blood Cinematic", NO_ICON));
      units.add(new UnitEntry(243, "Skeleton Giant", "Skeleton Giant", NO_ICON));
      units.add(new UnitEntry(244, "Skeleton Animal", "Skeleton Animal", NO_ICON));
      units.add(new UnitEntry(245, "Shipwreck", "Shipwreck", "boat g trireme icon.bmp"));
      units.add(new UnitEntry(246, "Ruins", "Ruins", "world column icon 64.bmp"));
      units.add(new UnitEntry(247, "Rotting Log", "Rotting Log", NO_ICON));
      units.add(new UnitEntry(248, "Underbrush", "Underbrush", NO_ICON));
      units.add(new UnitEntry(249, "Grass Tall", "Grass Tall", NO_ICON));
      units.add(new UnitEntry(250, "Rock Cliff", "Rock Cliff (test)", NO_ICON));
      units.add(new UnitEntry(251, "UI Range Indicator Egypt SFX", "UI Range Indicator Egyptian SFX", NO_ICON));
      units.add(new UnitEntry(252, "Harpy", "Harpy", "world hawk icon 64.bmp"));
      units.add(new UnitEntry(253, "Blowing Leaves", "Blowing Leaves", NO_ICON));
      units.add(new UnitEntry(254, "Hawksbill", "Hawksbill Turtle", NO_ICON));
      units.add(new UnitEntry(255, "Blood Flow", "Blood Flow", NO_ICON));
      units.add(new UnitEntry(256, "Ball of Fire invisible", "Ball of Fire", NO_ICON));
      units.add(new UnitEntry(257, "Splash Footprint", "Splash Footprint", NO_ICON));
      units.add(new UnitEntry(258, "Lava Bubbling", "Lava Bubbling", NO_ICON));
      units.add(new UnitEntry(259, "Wood Pile 1", "Wood Stockpile", NO_ICON));
      units.add(new UnitEntry(260, "Wood Pile 2", "Wood Stockpile", NO_ICON));
      units.add(new UnitEntry(261, "Wood Pile 3", "Wood Stockpile", NO_ICON));
      units.add(new UnitEntry(262, "Trident", "Poseidon Trident", NO_ICON));
      units.add(new UnitEntry(263, "Destruction Citadel", "Destruction Citadel", NO_ICON));
      units.add(new UnitEntry(264, "Forest Fire Attack", "Lightning Strike", NO_ICON));
      units.add(new UnitEntry(265, "UI Range Indicator Greek SFX", "UI Range Indicator Greek SFX", NO_ICON));
      units.add(new UnitEntry(266, "UI Range Indicator Norse SFX", "UI Range Indicator Norse SFX", NO_ICON));
      units.add(new UnitEntry(267, "Invisible Gate", "Invisible Gate", NO_ICON));
      units.add(new UnitEntry(268, "UI Army Banner Building", "UI Army Banner Building", NO_ICON));
      units.add(new UnitEntry(269, "Water decoration", "Water decoration", NO_ICON));
      units.add(new UnitEntry(270, "Footprint Cavalry", "Footprint Cavalry", NO_ICON));
      units.add(new UnitEntry(271, "Footprint Animal Large", "Footprint Animal Large", NO_ICON));
      units.add(new UnitEntry(272, "Footprint Animal Small", "Footprint Animal Small", NO_ICON));
      units.add(new UnitEntry(273, "Footprint Siege", "Footprint Siege", NO_ICON));
      units.add(new UnitEntry(274, "Evil Cloud SFX ", "Evil Cloud SFX", NO_ICON));
      units.add(new UnitEntry(275, "Smoke Giant", "Smoke", NO_ICON));
      units.add(new UnitEntry(276, "Crate Small", "Small Crate", NO_ICON));
      units.add(new UnitEntry(277, "Cinematic Wake", "Cinematic Wake", NO_ICON));
      units.add(new UnitEntry(278, "Weapons", "Weapons", NO_ICON));
      units.add(new UnitEntry(279, "Footprint Giant", "Footprint Giant", NO_ICON));
      units.add(new UnitEntry(280, "Footprint Elephant", "Footprint Elephant", NO_ICON));
      units.add(new UnitEntry(281, "Footprint Wheel", "Footprint Wheel", NO_ICON));
      units.add(new UnitEntry(282, "Footprint Hydra", "Footprint Hydra", NO_ICON));
      units.add(new UnitEntry(283, "Footprint Portable Ram", "Footprint Portable Ram", NO_ICON));
      units.add(new UnitEntry(284, "Footprint Scorpion", "Footprint Scorpion", NO_ICON));
      units.add(new UnitEntry(285, "Footprint Scarab", "Footprint Scarab", NO_ICON));
      units.add(new UnitEntry(286, "Savannah stump", "Savannah stump", NO_ICON));
      units.add(new UnitEntry(287, "Chicken Blood", "Chicken Blood", NO_ICON));
      units.add(new UnitEntry(288, "Crab Blood", "Crab Blood", NO_ICON));
      units.add(new UnitEntry(289, "Arkantos Boost SFX", "Arkantos Boost SFX", NO_ICON));
      units.add(new UnitEntry(290, "Tremor", "Thunder Clap", NO_ICON));
      units.add(new UnitEntry(291, "Meteorite", "Meteorite", NO_ICON));
      units.add(new UnitEntry(292, "Iceberg", "Seaweed", NO_ICON));
      units.add(new UnitEntry(293, "GaiaCreepFlowers", "Gaia Flowers", NO_ICON));
      units.add(new UnitEntry(294, "Deconstruct Unit", "Deconstruct Unit", NO_ICON));
      units.add(new UnitEntry(295, "Deconstruct Building", "Deconstruct Building", NO_ICON));
      units.add(new UnitEntry(296, "Chaos effect", "Chaos effect", NO_ICON));
      units.add(new UnitEntry(297, "Traitors effect", null, NO_ICON));
      units.add(new UnitEntry(298, "Meteorite death", "Meteorite death", NO_ICON));
      units.add(new UnitEntry(299, "Marsh Brush", "Marsh Brush", NO_ICON));
      units.add(new UnitEntry(300, "Tundra Brush", "Tundra Brush", NO_ICON));
      units.add(new UnitEntry(301, "Audrey Base", "Carnivora", "god power audrey icons 32.bmp"));
      units.add(new UnitEntry(302, "Audrey Water Base", "Carnivora", "god power audrey icons 32.bmp"));
      units.add(new UnitEntry(303, "Vortex start", null, NO_ICON));
      units.add(new UnitEntry(304, "Vortex finish", null, NO_ICON));
      units.add(new UnitEntry(305, "Marsh stump", "Marsh stump", NO_ICON));
      units.add(new UnitEntry(306, "Tundra stump", "Tundra stump", NO_ICON));
      units.add(new UnitEntry(307, "Fireball Launch Damage Effect", "Fireball Launch Damage Effect", NO_ICON));
      units.add(new UnitEntry(308, "Spider", "Spider", NO_ICON));
      units.add(new UnitEntry(309, "Implode Sphere", "Implode Sphere", NO_ICON));
      units.add(new UnitEntry(310, "Implode Sphere Effect", "Implode Sphere Effect", NO_ICON));
      units.add(new UnitEntry(311, "Implode Lightning Effect", "Implode Lightning Effect", NO_ICON));
      units.add(new UnitEntry(312, "Implode Pull Effect", "Implode Pull Effect", NO_ICON));
      units.add(new UnitEntry(313, "Javelin Flaming", "Javelin Flaming", NO_ICON));
      units.add(new UnitEntry(314, "Implode Shockwave", "Implode Shockwave", NO_ICON));
      units.add(new UnitEntry(315, "Spider Door", "Spider Door", NO_ICON));
      units.add(new UnitEntry(316, "Lampades Blood", "Lampades Blood", NO_ICON));
      units.add(new UnitEntry(317, "Acid Pool", "Acid Pool", NO_ICON));
      units.add(new UnitEntry(318, "Spider Warn", "Arrow Splash SFX", NO_ICON));
      units.add(new UnitEntry(319, "Gaia Forest effect", "Implode Pull Effect", NO_ICON));
      units.add(new UnitEntry(320, "Vortex start linked", null, NO_ICON));
      units.add(new UnitEntry(321, "Vortex finish linked", null, NO_ICON));
      units.add(new UnitEntry(322, "Vortex landing", null, NO_ICON));
      units.add(new UnitEntry(323, "Implode Debris", "Implode Debris", NO_ICON));
      units.add(new UnitEntry(324, "Titan Atlantean Footprint", "Titan Footprint", NO_ICON));
      units.add(new UnitEntry(325, "Timeshift out", "Timeshift out", NO_ICON));
      units.add(new UnitEntry(326, "Timeshift in", "Timeshift in", NO_ICON));
      units.add(new UnitEntry(327, "Tartarian Gate flame", "Implode Pull Effect", NO_ICON));
      units.add(new UnitEntry(328, "Heka Shockwave SFX", "Fire", NO_ICON));
      units.add(new UnitEntry(329, "Tartarian Gate creature effect", "Implode Pull Effect", NO_ICON));
      units.add(new UnitEntry(330, "Garrison Flag Sky Passage", "Garrison Flag Sky Passage", NO_ICON));
      units.add(new UnitEntry(331, "Lampades Bolt", "Lampades Bolt", NO_ICON));
      units.add(new UnitEntry(332, "Fire Siphon Fire", "Fire", NO_ICON));
      units.add(new UnitEntry(333, "Stymph Bird Feather", "Feather", NO_ICON));
      units.add(new UnitEntry(334, "Osiris Pyramid Dead", "Osiris Pyramid Dead", NO_ICON));
      units.add(new UnitEntry(335, "Rocket", "Rocket", NO_ICON));
      units.add(new UnitEntry(336, "UI Range Indicator Atlantean SFX", "UI Range Indicator Greek SFX", NO_ICON));
      units.add(new UnitEntry(337, "Tower Mirror Focuser", "Mirror Tower Focuser", "god power sentinel icon.bmp"));
      units.add(new UnitEntry(338, "Kronny Birth", "Kronny Birth", NO_ICON));
      units.add(new UnitEntry(339, "Mist Olympus", "Mist", NO_ICON));
      units.add(new UnitEntry(340, "Seagull High", "Seagull High", NO_ICON));
      units.add(new UnitEntry(341, "Seagull Low", "Seagull Low", NO_ICON));
      units.add(new UnitEntry(342, "Repeat Flag", "Repeat Flag", NO_ICON));
      units.add(new UnitEntry(343, "Ball of Fire Prometheus", "Ball of Fire", NO_ICON));
      units.add(new UnitEntry(344, "Shockwave stun effect", "Shockwave stun effect", NO_ICON));
      units.add(new UnitEntry(345, "Arkantos God Out", "Arkantos God Out", NO_ICON));
      units.add(new UnitEntry(346, "Olympus Temple SFX", "Olympus Temple SFX", NO_ICON));
      units.add(new UnitEntry(347, "Kronny Birth SFX", "Kronny Birth SFX", NO_ICON));
      units.add(new UnitEntry(348, "Lava Sheet", "Lava Pool", NO_ICON));
      units.add(new UnitEntry(349, "Sound Gaia SFX", "[NULL]", NO_ICON));
      units.add(new UnitEntry(350, "Footprint Prometheanbig", "Footprint Promethean", NO_ICON));
      units.add(new UnitEntry(351, "Footprint Prometheansmall", "Footprint Promethean", NO_ICON));
      units.add(new UnitEntry(352, "Cinematic Dead Bodies Xpack", "Cinematic Dead Bodies", NO_ICON));
      units.add(new UnitEntry(353, "Tartarian Rubble", "Tartarian Rubble", NO_ICON));
      units.add(new UnitEntry(354, "Titan Death", "Titan Death", NO_ICON));
      units.add(new UnitEntry(355, "Spearman", "Spearman", "infantry e spearman icon.bmp"));
      units.add(new UnitEntry(356, "Axeman", "Axeman", "infantry e axeman icon.bmp"));
      units.add(new UnitEntry(357, "Slinger", "Slinger", "archer e slinger icon.bmp"));
      units.add(new UnitEntry(358, "Raiding Cavalry", "Raiding Cavalry", "cavalry n raiding cavalry icon.bmp"));
      units.add(new UnitEntry(359, "Camelry", "Camelry", "cavalry e camelry icon.bmp"));
      units.add(new UnitEntry(360, "Dwarf", "Dwarf", "villager n dwarf icon.bmp"));
      units.add(new UnitEntry(361, "Barracks", "Barracks", "icon building barracks.bmp"));
      units.add(new UnitEntry(362, "Dock", "Dock", "icon building dock.bmp"));
      units.add(new UnitEntry(363, "Farm", "Farm", "icon building farm.bmp"));
      units.add(new UnitEntry(364, "Granary", "Granary", "icon building granary.bmp"));
      units.add(new UnitEntry(365, "Armory", "Armory", "icon building armory.bmp"));
      units.add(new UnitEntry(366, "Gate", "Gate", "building wall to gate icon.bmp"));
      units.add(new UnitEntry(367, "Market", "Market", "icon building market.bmp"));
      units.add(new UnitEntry(368, "Stable", "Stable", "icon building stable.bmp"));
      units.add(new UnitEntry(369, "Fortress", "Fortress", "icon building greek fortress.bmp"));
      units.add(new UnitEntry(370, "Monument", "Monument to Villagers", "building monument one icon.bmp"));
      units.add(new UnitEntry(371, "Siege Camp", "Siege Works", "icon building siege camp.bmp"));
      units.add(new UnitEntry(372, "Wonder", "Wonder", "icon building wonder.bmp"));
      units.add(new UnitEntry(373, "Cyclops", "Cyclops", "special g cyclops icon.bmp"));
      units.add(new UnitEntry(374, "Goat", "Goat", "animal goat icon.bmp"));
      units.add(new UnitEntry(375, "Wolf", "Wolf", "animal wolf icon.bmp"));
      units.add(new UnitEntry(376, "Pine", "Pine Tree", "icon pine tree.bmp"));
      units.add(new UnitEntry(377, "Storehouse", "Storehouse", "icon building storehouse.bmp"));
      units.add(new UnitEntry(378, "Scarab", "Scarab", "special e scarab icon.bmp"));
      units.add(new UnitEntry(379, "Ballista", "Ballista", "siege n ballista icon.bmp"));
      units.add(new UnitEntry(380, "Siege Tower", "Siege Tower", "siege e siege tower icon.bmp"));
      units.add(new UnitEntry(381, "Crocodile", "Crocodile", "animal crocodile icon.bmp"));
      units.add(new UnitEntry(382, "Hippo", "Hippopotamus", "animal hippo icon.bmp"));
      units.add(new UnitEntry(383, "Palm", "Palm Tree", "icon palm tree.bmp"));
      units.add(new UnitEntry(384, "Flag", "Flag", "flag icon 64.bmp"));
      units.add(new UnitEntry(385, "Anubite", "Anubite", "special e anubite icon.bmp"));
      units.add(new UnitEntry(386, "Bear", "Bear", "animal bear icon 64.bmp"));
      units.add(new UnitEntry(387, "Fire Giant", "Fire Giant", "special n fire giant icon.bmp"));
      units.add(new UnitEntry(388, "Locust Swarm", "Locust Swarm", NO_ICON));
      units.add(new UnitEntry(389, "Boar", "Boar", "animal boar icon.bmp"));
      units.add(new UnitEntry(390, "Frost Giant", "Frost Giant", "special n frost giant icon.bmp"));
      units.add(new UnitEntry(391, "Wall Long", "Wooden Wall", "improvement stone wall icon.bmp"));
      units.add(new UnitEntry(392, "Catapult", "Catapult", "siege e catapult icon.bmp"));
      units.add(new UnitEntry(393, "Caravan Norse", "Ox Caravan", "trade n caravan icon.bmp"));
      units.add(new UnitEntry(394, "Troll", "Troll", "special n trollkarien icon.bmp"));
      units.add(new UnitEntry(395, "Mountain Giant", "Mountain Giant", "special n mountain giant icon.bmp"));
      units.add(new UnitEntry(396, "Einheriar", "Einherjar", "special n einheriar icon.bmp"));
      units.add(new UnitEntry(397, "Kraken", "Kraken", "special n kraken icon.bmp"));
      units.add(new UnitEntry(398, "Sea Turtle", "War Turtle", "special g sea turtle icon.bmp"));
      units.add(new UnitEntry(399, "Valkyrie", "Valkyrie", "special n valkyrie icon.bmp"));
      units.add(new UnitEntry(400, "Battle Boar", "Battle Boar", "special n battle boar icon.bmp"));
      units.add(new UnitEntry(401, "Trireme", "Trireme", "boat g trireme icon.bmp"));
      units.add(new UnitEntry(402, "Fishing Ship Greek", "Fishing Ship", "boat g fishing boat icon.bmp"));
      units.add(new UnitEntry(403, "Bridge", "Bridge", NO_ICON));
      units.add(new UnitEntry(404, "Cow", "Cow", "animal cow icon.bmp"));
      units.add(new UnitEntry(405, "Giraffe", "Giraffe", "animal giraffe icon.bmp"));
      units.add(new UnitEntry(406, "Statue Pharaoh", "Pharaoh Statue", "building pharaoh statue icon 64.bmp"));
      units.add(new UnitEntry(407, "Torch", "Torch", "world torch icon 64.bmp"));
      units.add(new UnitEntry(408, "Pig", "Pig", "animal pig icon.bmp"));
      units.add(new UnitEntry(409, "Lazer Bear", "Lazer Bear", "animal bear icon.bmp"));
      units.add(new UnitEntry(410, "Zebra", "Zebra", "animal zebra icon.bmp"));
      units.add(new UnitEntry(411, "Water Buffalo", "Water Buffalo", "animal waterbuffalo icon.bmp"));
      units.add(new UnitEntry(412, "Gazelle", "Gazelle", "animal gazelle icon.bmp"));
      units.add(new UnitEntry(413, "Baboon", "Baboon", "animal baboon icon.bmp"));
      units.add(new UnitEntry(414, "Centaur", "Centaur", "special g centaur icon.bmp"));
      units.add(new UnitEntry(415, "Phoenix", "Phoenix", "special e phoenix icon.bmp"));
      units.add(new UnitEntry(416, "Manticore", "Manticore", "special g manticore icon.bmp"));
      units.add(new UnitEntry(417, "Chimera", "Chimera", "special g chimera icon.bmp"));
      units.add(new UnitEntry(418, "Sphinx", "Sphinx", "special e sphinx icon.bmp"));
      units.add(new UnitEntry(419, "Minotaur", "Minotaur", "special g minotaur icon.bmp"));
      units.add(new UnitEntry(420, "Hydra", "Hydra", "special g hydra icon.bmp"));
      units.add(new UnitEntry(421, "Chicken", "Chicken", "animal chicken icon.bmp"));
      units.add(new UnitEntry(422, "Monkey", "Monkey", "animal monkey icon.bmp"));
      units.add(new UnitEntry(423, "Colossus", "Colossus", "special g colossus icon.bmp"));
      units.add(new UnitEntry(424, "Mummy", "Mummy", "special e mummy icon.bmp"));
      units.add(new UnitEntry(425, "Roc", "Roc", "special e roc icon.bmp"));
      units.add(new UnitEntry(426, "Medusa", "Medusa", "special g medusa icon.bmp"));
      units.add(new UnitEntry(427, "Obelisk", "Obelisk", "world obelisk icon 64.bmp"));
      units.add(new UnitEntry(428, "Hades Door", "Hades Gate", "scenario hades gate icon 64.bmp"));
      units.add(new UnitEntry(429, "Ajax", "Ajax (Hero)", "hero g ajax.bmp"));
      units.add(new UnitEntry(430, "Arkantos", "Arkantos (Hero)", "special g arkantos icon.bmp"));
      units.add(new UnitEntry(431, "Gargarensis", "Gargarensis (Hero)", "scenario g gargarensis icon.bmp"));
      units.add(new UnitEntry(432, "Setna", "Setna (Hero)", "special e setna icon.bmp"));
      units.add(new UnitEntry(433, "Shaba Ka", "Kemsyt (Hero)", "scenario kemsyt icon.bmp"));
      units.add(new UnitEntry(434, "Odysseus", "Odysseus (Hero)", "hero g oddeysseus.bmp"));
      units.add(new UnitEntry(435, "Chiron", "Chiron (Hero)", "hero g chiron.bmp"));
      units.add(new UnitEntry(436, "Amanra", "Amanra (Hero)", "special e amanra icon.bmp"));
      units.add(new UnitEntry(437, "Wall Connector", "Wooden Wall", "improvement stone wall icon.bmp"));
      units.add(new UnitEntry(438, "Wall Short", "Wooden Wall", "improvement stone wall icon.bmp"));
      units.add(new UnitEntry(439, "Leviathan", "Leviathan", "special e leviathan icon.bmp"));
      units.add(new UnitEntry(440, "Statue Lion Right", "Lion Statue", "building lion statue icon 64.bmp"));
      units.add(new UnitEntry(441, "Statue Lion Left", "Lion Statue", "building lion statue icon 64.bmp"));
      units.add(new UnitEntry(442, "Egyptian Vulture", "Egyptian Vulture", "special e vulture icon.bmp"));
      units.add(new UnitEntry(443, "Reginleif", "Reginleif (Hero)", "scenario n reginleif icon.bmp"));
      units.add(new UnitEntry(444, "Scout", "Kataskopos (Scout)", "cavalry g scout icon.bmp"));
      units.add(new UnitEntry(445, "Archery Range", "Archery Range", "icon building archery range.bmp"));
      units.add(new UnitEntry(446, "Scorpion Man", "Scorpion Man", "special e scorpion man icon.bmp"));
      units.add(new UnitEntry(447, "Minion", "Minion", "special e minion icon.bmp"));
      units.add(new UnitEntry(448, "Fish - Perch", "Perch", "animal fish icon.bmp"));
      units.add(new UnitEntry(449, "Great Box", "Osiris Piece Box", "trade e caravan icon.bmp"));
      units.add(new UnitEntry(450, "Great Box Cart", "Osiris Piece Cart", "trade e caravan icon.bmp"));
      units.add(new UnitEntry(451, "Gold Mine", "Large Gold Mine", "icon gold mine 64.bmp"));
      units.add(new UnitEntry(452, "Kamos", "Kamos (Hero)", "scenario g kamos icon.bmp"));
      units.add(new UnitEntry(453, "Oak Tree", "Oak Tree", "icon oak tree.bmp"));
      units.add(new UnitEntry(454, "Pyramid Large", "Osiris Pyramid", "building osiris pyramid icon 64.bmp"));
      units.add(new UnitEntry(455, "Pyramid Small", "Pyramid", "building osiris pyramid icon 64.bmp"));
      units.add(new UnitEntry(456, "Lion", "Lion", "animal lion icon.bmp"));
      units.add(new UnitEntry(457, "Rhinocerous", "Rhinoceros", "animal rhino icon.bmp"));
      units.add(new UnitEntry(458, "Hyena", "Hyena", "animal hyena icon.bmp"));
      units.add(new UnitEntry(459, "Crowned Crane", "Crowned Crane", "animal crowned crane icon.bmp"));
      units.add(new UnitEntry(460, "Aurochs", "Aurochs", "animal aurochs icon.bmp"));
      units.add(new UnitEntry(461, "Fish - Mahi", "Mahi mahi", "animal fish icon.bmp"));
      units.add(new UnitEntry(462, "Fish - Salmon", "Salmon", "animal fish icon.bmp"));
      units.add(new UnitEntry(463, "Giant Duck-billed Platypus", "Giant Duck-billed Platypus", NO_ICON));
      units.add(new UnitEntry(464, "Temple", "Temple", "icon building temple.bmp"));
      units.add(new UnitEntry(465, "House", "House", "icon building house.bmp"));
      units.add(new UnitEntry(466, "Tent", "Tent", "world tent icon 64.bmp"));
      units.add(new UnitEntry(467, "Elephant", "Elephant", "animal elephant icon.bmp"));
      units.add(new UnitEntry(468, "Tunnel", "Underworld Passage", "god power underworld passage icon.bmp"));
      units.add(new UnitEntry(469, "Tower", "Sentry Tower", "building sentry tower icon.bmp"));
      units.add(new UnitEntry(470, "Settlement", "Settlement", "building settlement icon.bmp"));
      units.add(new UnitEntry(471, "Pegasus", "Pegasus", "special g pegasus icon.bmp"));
      units.add(new UnitEntry(472, "Scylla", "Scylla", "special g scylla icon.bmp"));
      units.add(new UnitEntry(473, "Avenger", "Avenger", "special e avenger icon.bmp"));
      units.add(new UnitEntry(474, "Raven", "Raven", "special n raven icon.bmp"));
      units.add(new UnitEntry(475, "Excavation", "Excavation", "icon building mining camp.bmp"));
      units.add(new UnitEntry(476, "Guardian", "Guardian", "scenario sleeping guardian icon 64.bmp"));
      units.add(new UnitEntry(477, "Guardian Sleeping", "Sleeping Guardian", "scenario sleeping guardian icon 64.bmp"));
      units.add(new UnitEntry(478, "Sword Bearers", "Sword Bearers", "scenario swordbearers icon.bmp"));
      units.add(new UnitEntry(479, "Deer", "Deer", "animal deer icon.bmp"));
      units.add(new UnitEntry(480, "Settlement Level 1", "Town Center", NO_ICON));
      units.add(new UnitEntry(481, "Ox Cart", "Ox Cart", "villager n oxcart icon.bmp"));
      units.add(new UnitEntry(482, "Fence Stone", "Stone Fence", "icon building wooden fence 64.bmp"));
      units.add(new UnitEntry(483, "Fence Wood", "Wooden Fence", "icon building wooden fence 64.bmp"));
      units.add(new UnitEntry(484, "Villager Norse", "Gatherer", "villager n male icon.bmp"));
      units.add(new UnitEntry(485, "Longhouse", "Longhouse", "icon building barracks.bmp"));
      units.add(new UnitEntry(486, "Academy", "Military Academy", "icon building barracks.bmp"));
      units.add(new UnitEntry(487, "Villager Greek", "Villager", "villager g male icon.bmp"));
      units.add(new UnitEntry(488, "Portable Ram", "Portable Ram", "siege n portable ram icon.bmp"));
      units.add(new UnitEntry(489, "Hill Fort", "Hill Fort", "icon building norse fortress.bmp"));
      units.add(new UnitEntry(490, "Villager Egyptian", "Laborer", "villager e male icon.bmp"));
      units.add(new UnitEntry(491, "Throwing Axeman", "Throwing Axeman", "archer n throwing axeman icon.bmp"));
      units.add(new UnitEntry(492, "Ulfsark", "Ulfsark", "infantry n ulfsark icon.bmp"));
      units.add(new UnitEntry(493, "Huskarl", "Huskarl", "infantry n huskarl icon.bmp"));
      units.add(new UnitEntry(494, "Shrine", "Shrine", "icon building shrine 64.bmp"));
      units.add(new UnitEntry(495, "Hero Norse", "Hersir (Hero)", "hero n hersir icon.bmp"));
      units.add(new UnitEntry(496, "Hero Greek Achilles", "Achilles (Hero)", "hero g achilles.bmp"));
      units.add(new UnitEntry(497, "Pharaoh", "Pharaoh", "unit e pharaoh icon.bmp"));
      units.add(new UnitEntry(498, "Lumber Camp", "Lumber Camp", "icon building lumbercamp.bmp"));
      units.add(new UnitEntry(499, "Mining Camp", "Mining Camp", "icon building mining camp.bmp"));
      units.add(new UnitEntry(500, "Hero Greek Odysseus", "Odysseus (Hero)", "hero g oddeysseus.bmp"));
      units.add(new UnitEntry(501, "Hero Greek Chiron", "Chiron (Hero)", "hero g chiron.bmp"));
      units.add(new UnitEntry(502, "Hero Greek Polyphemus", "Polyphemus (Hero)", "hero g polyphemus.bmp"));
      units.add(new UnitEntry(503, "Hoplite", "Hoplite", "infantry g hoplite icon.bmp"));
      units.add(new UnitEntry(504, "Hypaspist", "Hypaspist", "infantry g hypaspist icon.bmp"));
      units.add(new UnitEntry(505, "Hippikon", "Hippikon", "cavalry g hippikon icon.bmp"));
      units.add(new UnitEntry(506, "Prodromos", "Prodromos", "cavalry g prodromos icon.bmp"));
      units.add(new UnitEntry(507, "Peltast", "Peltast", "archer g peltast icon.bmp"));
      units.add(new UnitEntry(508, "Toxotes", "Toxotes", "archer g toxotes icon.bmp"));
      units.add(new UnitEntry(509, "Petrobolos", "Petrobolos", "siege g petrobolos icon.bmp"));
      units.add(new UnitEntry(510, "Helepolis", "Helepolis", "siege g helepolis icon.bmp"));
      units.add(new UnitEntry(511, "Priest", "Priest (Hero)", "special e priest icon.bmp"));
      units.add(new UnitEntry(512, "Migdol Stronghold", "Migdol Stronghold", "icon building egypt migdol.bmp"));
      units.add(new UnitEntry(513, "Chariot Archer", "Chariot Archer", "cavalry e chariot archer icon.bmp"));
      units.add(new UnitEntry(514, "Myrmidon", "Myrmidon", "infantry g myrmidon icon.bmp"));
      units.add(new UnitEntry(515, "Hetairoi", "Hetairoi", "cavalry g hetairoi icon.bmp"));
      units.add(new UnitEntry(516, "Cataphract", "Cataphract", "cavalry g cataphract icon.bmp"));
      units.add(new UnitEntry(517, "Mercenary", "Mercenary", "infantry e mercenary icon.bmp"));
      units.add(new UnitEntry(518, "Monument 2", "Monument to Soldiers", "building monument two icon.bmp"));
      units.add(new UnitEntry(519, "Monument 3", "Monument to Priests", "building monument three icon.bmp"));
      units.add(new UnitEntry(520, "Monument 4", "Monument to Pharaohs", "building monument four icon.bmp"));
      units.add(new UnitEntry(521, "Monument 5", "Monument to Gods", "building monument five icon.bmp"));
      units.add(new UnitEntry(522, "Statue of Major God", "Major God Statue", "scenario god statue.bmp"));
      units.add(new UnitEntry(523, "Dwarven Forge", "Dwarven Forge", "icon building armory.bmp"));
      units.add(new UnitEntry(524, "Folstag Flag Bearer", "Folstag Flag Bearer", "scenario folstag icon.bmp"));
      units.add(new UnitEntry(525, "Trojan Horse", "Trojan Horse", "siege trojan horse icon 64.bmp"));
      units.add(new UnitEntry(526, "Berry Bush", "Berry Bush", "world berry bush icon 64.bmp"));
      units.add(new UnitEntry(527, "Bolder Wall", "Boulder Wall", "scenario boulder wall icon 64.bmp"));
      units.add(new UnitEntry(528, "Mercenary Cavalry", "Mercenary Cavalry", "cavalry e mercenary icon.bmp"));
      units.add(new UnitEntry(529, "Pirate Ship", "Pirate Ship", "scenario n pirate ship icon 64.bmp"));
      units.add(new UnitEntry(530, "Gate Ram", "Giant Gate Ram", "special g hades ram icon 64.bmp"));
      units.add(new UnitEntry(531, "Jarl", "Jarl", "cavalry n jarl icon.bmp"));
      units.add(new UnitEntry(532, "Wall Long Destruction SFX", "Wall Long Destruction SFX", NO_ICON));
      units.add(new UnitEntry(533, "Wall Short Destruction SFX", "Wall Short Destruction SFX", NO_ICON));
      units.add(new UnitEntry(534, "Wall Connector Destruction SFX", "Wall Connector Destruction SFX", NO_ICON));
      units.add(new UnitEntry(535, "Outpost", "Obelisk", "building outpost icon.bmp"));
      units.add(new UnitEntry(536, "Transport Ship Greek", "Transport Ship", "boat g transport icon.bmp"));
      units.add(new UnitEntry(537, "Kebenit", "Kebenit", "boat e kebenit icon.bmp"));
      units.add(new UnitEntry(538, "Longboat", "Longboat", "boat n longboat icon.bmp"));
      units.add(new UnitEntry(539, "Lighthouse", "Lighthouse", "building lighthouse icon.bmp"));
      units.add(new UnitEntry(540, "Hero Boar", "Boar (Arkantos)", "animal boar icon.bmp"));
      units.add(new UnitEntry(541, "Hero Greek Heracles", "Heracles (Hero)", "hero g heracles.bmp"));
      units.add(new UnitEntry(542, "Hero Greek Jason", "Jason (Hero)", "hero g jason.bmp"));
      units.add(new UnitEntry(543, "Fishing Ship Norse", "Fishing Ship", "boat n fishing boat icon.bmp"));
      units.add(new UnitEntry(544, "Fishing Ship Egyptian", "Fishing Ship", "boat e fishing boat icon.bmp"));
      units.add(new UnitEntry(545, "Transport Ship Egyptian", "Transport Ship", "boat e transport icon.bmp"));
      units.add(new UnitEntry(546, "Troy Gate", "Gate of Troy", "building wall to gate icon.bmp"));
      units.add(new UnitEntry(547, "Troy Wall Connector", "Wall of Troy", "icon building wooden fence 64.bmp"));
      units.add(new UnitEntry(548, "Troy Wall Long", "Wall of Troy", "icon building wooden fence 64.bmp"));
      units.add(new UnitEntry(549, "Troy Wall Short", "Wall of Troy", "icon building wooden fence 64.bmp"));
      units.add(new UnitEntry(550, "Hero Greek Hippolyta", "Hippolyta (Hero)", "hero g hippolyta.bmp"));
      units.add(new UnitEntry(551, "Hero Greek Theseus", "Theseus (Hero)", "hero g theseus.bmp"));
      units.add(new UnitEntry(552, "Hero Greek Bellerophon", "Bellerophon (Hero)", "hero g bellerophon.bmp"));
      units.add(new UnitEntry(553, "Hero Greek Ajax", "Ajax (Hero)", "hero g ajax.bmp"));
      units.add(new UnitEntry(554, "Hero Greek Atalanta", "Atalanta (Hero)", "hero g atalanta.bmp"));
      units.add(new UnitEntry(555, "Hero Greek Perseus", "Perseus (Hero)", "hero g perseus icon.bmp"));
      units.add(new UnitEntry(556, "Flying Purple Hippo", "Flying Purple Hippo", "animal hippo icon.bmp"));
      units.add(new UnitEntry(557, "Caravan Greek", "Donkey Caravan", "trade g caravan icon.bmp"));
      units.add(new UnitEntry(558, "Caravan Egyptian", "Camel Caravan", "trade e caravan icon.bmp"));
      units.add(new UnitEntry(559, "Relic", "Relic", "scenario folstag icon.bmp"));
      units.add(new UnitEntry(560, "Skult", "Skult", "infantry n skult icon.bmp"));
      units.add(new UnitEntry(561, "Bolder Rolling", "Boulder", "scenario boulder wall icon 64.bmp"));
      units.add(new UnitEntry(562, "Gold Mine Small", "Medium Gold Mine", "icon gold mine 64.bmp"));
      units.add(new UnitEntry(563, "Pine Snow", "Snowy Pine", "icon pine tree.bmp"));
      units.add(new UnitEntry(564, "Circe", "Circe (Hero)", "special g circe icon.bmp"));
      units.add(new UnitEntry(565, "Stop Combat", "Stop Combat", NO_ICON));
      units.add(new UnitEntry(566, "Naval Shipyard", "Naval Shipyard", "icon building dock.bmp"));
      units.add(new UnitEntry(567, "Ramming Ship Greek", "Pentekonter", "boat g pentekonter icon.bmp"));
      units.add(new UnitEntry(568, "Siege Ship Greek", "Juggernaut", "boat g juggernaught icon.bmp"));
      units.add(new UnitEntry(569, "Hero Greek Argo", "The Argo (Hero)", "special g argo icon.bmp"));
      units.add(new UnitEntry(570, "Ramming Ship Norse", "Drakkar", "boat n drakkar icon.bmp"));
      units.add(new UnitEntry(571, "Ramming Ship Egyptian", "Ramming Galley", "boat e ramming galley icon.bmp"));
      units.add(new UnitEntry(572, "Siege Ship Norse", "Dragon Ship", "boat n dragonship icon.bmp"));
      units.add(new UnitEntry(573, "Siege Ship Egyptian", "War Barge", "boat e warbarge icon.bmp"));
      units.add(new UnitEntry(574, "Shade", "Shade", "special g shade icon.bmp"));
      units.add(new UnitEntry(575, "Animal Attractor", "Lure", "god power animal magnet icon.bmp"));
      units.add(new UnitEntry(576, "Healing Spring Object", "Healing Spring", "god power healing spring icon.bmp"));
      units.add(new UnitEntry(577, "Serpent", "Serpent", "god power snake plague icon.bmp"));
      units.add(new UnitEntry(578, "Sentinel Main", "Sentinel", "god power sentinel icon.bmp"));
      units.add(new UnitEntry(579, "Citadel Center", "Citadel Center", "god power citadel icon.bmp"));
      units.add(new UnitEntry(580, "Walking Woods Pine", "Walking Pine", "god power walking woods icon.bmp"));
      units.add(new UnitEntry(581, "Walking Woods Oak", "Walking Oak", "god power walking woods icon.bmp"));
      units.add(new UnitEntry(582, "Walking Woods Palm", "Walking Palm", "god power walking woods icon.bmp"));
      units.add(new UnitEntry(583, "Hero Ragnorok", "Hero of Ragnarok", "hero n ragnarok icon.bmp"));
      units.add(new UnitEntry(584, "Nidhogg", "Nidhogg", "special n nidhogg icon.bmp"));
      units.add(new UnitEntry(585, "Fimbulwinter Wolf", "Fimbulwinter Wolf", "animal wolf icon.bmp"));
      units.add(new UnitEntry(586, "Plenty Vault", "Plenty Vault", "god power plenty icon.bmp"));
      units.add(new UnitEntry(587, "Pharaoh of Osiris", "Son of Osiris (Hero)", "special e son of osiris icon.bmp"));
      units.add(new UnitEntry(588, "Gold Mine Dwarven", "Dwarven Gold Mine", "icon gold mine 64.bmp"));
      units.add(new UnitEntry(589, "Fenris Wolf", "Fenris Wolf Brood", "special n fenris wolf icon.bmp"));
      units.add(new UnitEntry(590, "Athena", "Athena", "improvement athena icon.bmp"));
      units.add(new UnitEntry(591, "Walrus", "Walrus", "animal walrus icon.bmp"));
      units.add(new UnitEntry(592, "Wadjet", "Wadjet", "special e wadjet icon.bmp"));
      units.add(new UnitEntry(593, "Petsuchos", "Petsuchos", "special e petosuchus icon.bmp"));
      units.add(new UnitEntry(594, "Nemean Lion", "Nemean Lion", "special g nemean lion icon.bmp"));
      units.add(new UnitEntry(595, "Agamemnon", "Agamemnon (Hero)", "special g agamemnon icon.bmp"));
      units.add(new UnitEntry(596, "Theocrat", "Theocrat", "special g god statue icon 64.bmp"));
      units.add(new UnitEntry(597, "Shade of Hades", "Hades Shade", "special g shade icon.bmp"));
      units.add(new UnitEntry(598, "Atlantis Wall Connector", "Wall of Atlantis", "improvement stone wall icon.bmp"));
      units.add(new UnitEntry(599, "Atlantis Wall Long", "Wall of Atlantis", "improvement stone wall icon.bmp"));
      units.add(new UnitEntry(600, "Atlantis Gate", "Atlantis Gate", "building wall to gate icon.bmp"));
      units.add(new UnitEntry(601, "Tamarisk Tree", "Tamarisk Tree", "scenario tamarisk tree icon 64.bmp"));
      units.add(new UnitEntry(602, "Phoenix Egg", "Phoenix Egg", "special e phoenix egg icon 64.bmp"));
      units.add(new UnitEntry(603, "Polar Bear", "Polar Bear", "animal polar bear icon.bmp"));
      units.add(new UnitEntry(604, "Walking Woods Pine Snow", "Walking Snowy Pine", "god power walking woods icon.bmp"));
      units.add(new UnitEntry(605, "Caribou", "Caribou", "animal caribou icon.bmp"));
      units.add(new UnitEntry(606, "Elk", "Elk", "animal elk icon.bmp"));
      units.add(new UnitEntry(607, "Pig Special", "Pig", "animal pig icon.bmp"));
      units.add(new UnitEntry(608, "Titan Bad", "Living Poseidon Statue", "special g god statue icon 64.bmp"));
      units.add(new UnitEntry(609, "Palm Burning", "Palm Burning", "icon palm tree.bmp"));
      units.add(new UnitEntry(610, "Oak Tree Burning", "Oak Tree Burning", "icon oak tree.bmp"));
      units.add(new UnitEntry(611, "Pine Burning", "Pine Burning", "icon pine tree.bmp"));
      units.add(new UnitEntry(612, "Great Box Cart 2", "Osiris Piece Cart", "trade e caravan icon.bmp"));
      units.add(new UnitEntry(613, "Transport Ship Norse", "Transport Ship", "boat n transport icon.bmp"));
      units.add(new UnitEntry(614, "Thor Hammer Haft", "Thor's Hammer Haft", "scenario thors hammer icon 64.bmp"));
      units.add(new UnitEntry(615, "Thor Hammer Head", "Thor's Hammer Head", "scenario thors hammer icon 64.bmp"));
      units.add(new UnitEntry(616, "Pine Snow Burning", "Snowy Pine Burning", "icon pine tree.bmp"));
      units.add(new UnitEntry(617, "War Elephant", "War Elephant", "cavalry war elephant icon.bmp"));
      units.add(new UnitEntry(618, "Oak Autumn", "Autumn Oak", "icon oak tree.bmp"));
      units.add(new UnitEntry(619, "Brokk", "Brokk (Hero)", "scenario brokk icon.bmp"));
      units.add(new UnitEntry(620, "Eitri", "Eitri (Hero)", "scenario eitri icon.bmp"));
      units.add(new UnitEntry(621, "Dwarf Foundry", "Dwarven Armory", "icon building armory.bmp"));
      units.add(new UnitEntry(622, "Hippocampus", "Hippocampus", "special g hippocampus icon.bmp"));
      units.add(new UnitEntry(623, "Oak Autumn Burning", "Autumn Oak", "icon oak tree.bmp"));
      units.add(new UnitEntry(624, "Skraeling", "Skraeling", "infantry n ulfsark icon.bmp"));
      units.add(new UnitEntry(625, "Underworld Passage SPC", "Underworld Passage", "god power underworld passage icon.bmp"));
      units.add(new UnitEntry(626, "Carcinos", "Carcinos", "special g carcinos icon.bmp"));
      units.add(new UnitEntry(627, "Jormund Elver", "Jormund Elver", "special n jormund brood icon.bmp"));
      units.add(new UnitEntry(628, "Militia", "Militia", "infantry g militia icon.bmp"));
      units.add(new UnitEntry(629, "Kastor", "Kastor", "special g kastor icon.bmp"));
      units.add(new UnitEntry(630, "Sea Snake", "Sea Snake", "god power snake plague icon.bmp"));
      units.add(new UnitEntry(631, "Old Man", "Old Man", "villager g male icon 64.bmp"));
      units.add(new UnitEntry(632, "Jail Wall", "Jail Wall", "icon building wooden fence 64.bmp"));
      units.add(new UnitEntry(633, "Dig Pile", "Dig Pile", "scenario dig pile icon 64.bmp"));
      units.add(new UnitEntry(634, "Golden Fleece", "Golden Fleece", "animal goat icon.bmp"));
      units.add(new UnitEntry(635, "Temple Underworld", "Temple of the Gods", "icon building temple.bmp"));
      units.add(new UnitEntry(636, "Arkantosman", "Arkantos (Hero)", "special g arkantos icon.bmp"));
      units.add(new UnitEntry(637, "Bolder Rolling Dead", "Boulder Rolling Dead", "scenario boulder wall icon 64.bmp"));
      units.add(new UnitEntry(638, "Bolder Rolling 2", "Boulder", "scenario boulder wall icon 64.bmp"));
      units.add(new UnitEntry(639, "Pine Dead", "Pine Dead", "icon pine tree.bmp"));
      units.add(new UnitEntry(640, "Gate Ram 2", "Giant Gate Ram", "special g hades ram icon 64.bmp"));
      units.add(new UnitEntry(641, "Mini Atlantis", "Atlantis", NO_ICON));
      units.add(new UnitEntry(642, "Atlantis Tile", "Atlantis Tile", NO_ICON));
      units.add(new UnitEntry(643, "Atlantis Tile Dead", "Atlantis Tile Dead", "scenario boulder wall icon 64.bmp"));
      units.add(new UnitEntry(644, "Well of Urd", "Well of Urd", "god power underworld passage icon.bmp"));
      units.add(new UnitEntry(645, "Troy Gate Dead", "Gate of Troy", "building wall to gate icon.bmp"));
      units.add(new UnitEntry(646, "Plenty Vault KOTH", "Plenty Vault", "god power plenty icon.bmp"));
      units.add(new UnitEntry(647, "Poseidon Statue", "Statue of Poseidon", "special g god statue icon 64.bmp"));
      units.add(new UnitEntry(648, "Pharaoh Secondary", "Second Pharaoh", "unit e pharaoh icon.bmp"));
      units.add(new UnitEntry(649, "Savannah Tree", "Savannah Tree", "icon savannah tree.bmp"));
      units.add(new UnitEntry(650, "Golden Lion", "Golden Lion", "animal lion icon.bmp"));
      units.add(new UnitEntry(651, "Monkey Relic", "Relic Monkey", "animal monkey icon.bmp"));
      units.add(new UnitEntry(652, "Ghost Ship", "Lost Ship", "boat e kebenit icon.bmp"));
      units.add(new UnitEntry(653, "Shade of Erebus", "Hades Shade", "special g shade icon.bmp"));
      units.add(new UnitEntry(654, "Bandit Migdol", "Bandit Migdol", "icon building egypt migdol.bmp"));
      units.add(new UnitEntry(655, "Gold Mine Tiny", "Small Gold Mine", "icon gold mine 64.bmp"));
      units.add(new UnitEntry(656, "Wall Medium", "Wooden Wall", "improvement stone wall icon.bmp"));
      units.add(new UnitEntry(657, "Statue of Lightning", "Statue of Lightning", "scenario god statue.bmp"));
      units.add(new UnitEntry(658, "Crossbowman", "Gastraphetes", "archer g crossbowman icon.bmp"));
      units.add(new UnitEntry(659, "Fence Iron", "Iron Fence", "icon building wooden fence 64.bmp"));
      units.add(new UnitEntry(660, "Charon Ferry", "Charon Ferry", "boat e kebenit icon.bmp"));
      units.add(new UnitEntry(661, "Hero Boar 2", "Boar (Ajax)", "animal boar icon.bmp"));
      units.add(new UnitEntry(662, "Taproot", "Taproot", "scenario taproot icon 64.bmp"));
      units.add(new UnitEntry(663, "Female", "Greta Forkbeard", "scenario n greta forkbeard icon.bmp"));
      units.add(new UnitEntry(664, "Theris", "Theris (Hero)", "special e anubite icon.bmp"));
      units.add(new UnitEntry(665, "Ornlu", "Ornlu (Hero)", "special n fenris wolf icon.bmp"));
      units.add(new UnitEntry(666, "Polaris", "Polaris (Hero)", "animal polar bear icon.bmp"));
      units.add(new UnitEntry(667, "Tamarisk Tree Dead", "Tamarisk Tree", "scenario tamarisk tree icon 64.bmp"));
      units.add(new UnitEntry(668, "Prisoner", "Prisoner", "villager g male icon 64.bmp"));
      units.add(new UnitEntry(669, "Folstag Flag", "Folstag Flag", "scenario folstag flag.bmp"));
      units.add(new UnitEntry(670, "Undermine Building Destruction SFX", "Wall Long Destruction SFX", NO_ICON));
      units.add(new UnitEntry(671, "Pine Dead Burning", "Pine Dead Burning", "icon pine tree.bmp"));
      units.add(new UnitEntry(672, "Ape of Set", "Ape of Set", "animal baboon icon.bmp"));
      units.add(new UnitEntry(673, "Gazelle of Set", "Gazelle of Set", "animal gazelle icon.bmp"));
      units.add(new UnitEntry(674, "Hyena of Set", "Hyena of Set", "animal hyena icon.bmp"));
      units.add(new UnitEntry(675, "Crocodile of Set", "Crocodile of Set", "animal crocodile icon.bmp"));
      units.add(new UnitEntry(676, "Hippo of Set", "Hippo of Set", "animal hippo icon.bmp"));
      units.add(new UnitEntry(677, "Rhinoceros of Set", "Rhinoceros of Set", "animal rhino icon.bmp"));
      units.add(new UnitEntry(678, "Giraffe of Set", "Giraffe of Set", "animal giraffe icon.bmp"));
      units.add(new UnitEntry(679, "Kraken SPC", "Kraken", "special n kraken icon.bmp"));
      units.add(new UnitEntry(680, "Savannah Tree Burning", "Autumn Oak", "icon savannah tree.bmp"));
      units.add(new UnitEntry(681, "Wonder SPC", "Wonder", "icon building wonder.bmp"));
      units.add(new UnitEntry(682, "Monkey Raft", "Monkey Raft", "boat g trireme icon.bmp"));
      units.add(new UnitEntry(683, "Forkboy", "Forkboy", "infantry e axeman icon.bmp"));
      units.add(new UnitEntry(684, "Walking Berry Bush", "Walking Berry Bush", "god power walking woods icon.bmp"));
      units.add(new UnitEntry(685, "Chicken Exploding", "Methane Chicken", "animal chicken icon.bmp"));
      units.add(new UnitEntry(686, "Walking Woods Savannah", "Walking Acacia", "god power walking woods icon.bmp"));
      units.add(new UnitEntry(687, "Erebus Tree", "Erebus Tree", "world dead tree icon 64.bmp"));
      units.add(new UnitEntry(688, "Villager Atlantean", "Citizen", "villager x male icons 32.bmp"));
      units.add(new UnitEntry(689, "Manor", "Manor", "building manor icons 32.bmp"));
      units.add(new UnitEntry(690, "Villager Atlantean Hero", "Citizen (Hero)", "villager x male hero icons 32.bmp"));
      units.add(new UnitEntry(691, "Swordsman", "Murmillo", "infantry x murmillo icons 32.bmp"));
      units.add(new UnitEntry(692, "Trident Soldier", "Destroyer", "infantry x protector icons 32.bmp"));
      units.add(new UnitEntry(693, "Trident Soldier Hero", "Destroyer (Hero)", "infantry x protector hero icons 32.bmp"));
      units.add(new UnitEntry(694, "Swordsman Hero", "Murmillo (Hero)", "infantry x murmillo hero icons 32.bmp"));
      units.add(new UnitEntry(695, "Fishing Ship Atlantean", "Fishing Ship", "boat x fishing ship atlantean icons 32.bmp"));
      units.add(new UnitEntry(696, "Bireme", "Bireme", "boat x bireme icons 32.bmp"));
      units.add(new UnitEntry(697, "Transport Ship Atlantean", "Transport Ship", "boat x transport ship atlantean icons 32.bmp"));
      units.add(new UnitEntry(698, "Fire Ship Atlantean", "Fireship", "boat x fire ship atlantean icons 32.bmp"));
      units.add(new UnitEntry(699, "Siege Ship Atlantean", "Siege Bireme", "boat x siege ship atlantean icons 32.bmp"));
      units.add(new UnitEntry(700, "Lancer", "Contarius", "cavalry x lancer icons 32.bmp"));
      units.add(new UnitEntry(701, "Lancer Hero", "Contarius (Hero)", "cavalry x lancer hero icons 32.bmp"));
      units.add(new UnitEntry(702, "Counter Building", "Counter Barracks", "building specialist icons 32.bmp"));
      units.add(new UnitEntry(703, "Chieroballista", "Cheiroballista", "siege x chieroballista icons 32.bmp"));
      units.add(new UnitEntry(704, "Fire Siphon", "Fire Siphon", "siege x fire siphon icons 32.bmp"));
      units.add(new UnitEntry(705, "Caravan Atlantean", "Llama Caravan", "trade x caravan icons 32.bmp"));
      units.add(new UnitEntry(706, "Palace", "Palace", "building palace icons 32.bmp"));
      units.add(new UnitEntry(707, "Royal Guard", "Fanatic", "infantry x fanatic icons 32.bmp"));
      units.add(new UnitEntry(708, "Royal Guard Hero", "Fanatic (Hero)", "infantry x fanatic hero icons 32.bmp"));
      units.add(new UnitEntry(709, "Sky Passage", "Sky Passage", "building skytemple icons 32.bmp"));
      units.add(new UnitEntry(710, "Titan Atlantean", "Titan", "special x atlantean titan icons 32.bmp"));
      units.add(new UnitEntry(711, "Barracks Atlantean", "Military Barracks", "building barracks icons 32.bmp"));
      units.add(new UnitEntry(712, "Archer Atlantean", "Arcus", "archer x arcus icons 32.bmp"));
      units.add(new UnitEntry(713, "Archer Atlantean Hero", "Arcus (Hero)", "archer x arcus hero icons 32.bmp"));
      units.add(new UnitEntry(714, "Maceman", "Katapeltes", "infantry x maceman icons 32.bmp"));
      units.add(new UnitEntry(715, "Maceman Hero", "Katapeltes (Hero)", "infantry x maceman hero icons 32.bmp"));
      units.add(new UnitEntry(716, "Javelin Cavalry", "Turma", "cavalry x jav cav icons 32.bmp"));
      units.add(new UnitEntry(717, "Javelin Cavalry Hero", "Turma (Hero)", "cavalry x jav cav hero icons 32.bmp"));
      units.add(new UnitEntry(718, "Audrey", "Carnivora", "god power audrey icons 32.bmp"));
      units.add(new UnitEntry(719, "Audrey Water", "Carnivora", "god power audrey icons 32.bmp"));
      units.add(new UnitEntry(720, "Guild", "Economic Guild", "building guild icons 32.bmp"));
      units.add(new UnitEntry(721, "Volcano", "Volcano", NO_ICON));
      units.add(new UnitEntry(722, "Behemoth", "Behemoth", "special x behemoth icons 32.bmp"));
      units.add(new UnitEntry(723, "Flying Medic", "Caladria", "special x flying medic icons 32.bmp"));
      units.add(new UnitEntry(724, "Tower Mirror", "Mirror Tower", "building tower mirror icons 32.bmp"));
      units.add(new UnitEntry(725, "Promethean", "Promethean", "special x promethean icons 32.bmp"));
      units.add(new UnitEntry(726, "Servant", "Servant", "special x servant icons 32.bmp"));
      units.add(new UnitEntry(727, "Satyr", "Satyr", "special x satyr icons 32.bmp"));
      units.add(new UnitEntry(728, "Stymphalian Bird", "Stymphalian Bird", "special x stymphalian bird icons 32.bmp"));
      units.add(new UnitEntry(729, "Automaton", "Automaton", "special x automaton icons 32.bmp"));
      units.add(new UnitEntry(730, "Man O War", "Man O' War", "special x man o war icons 32.bmp"));
      units.add(new UnitEntry(731, "Promethean Small", "Promethean Offspring", "special x small promethean icons 32.bmp"));
      units.add(new UnitEntry(732, "Oracle Hero", "Oracle (Hero)", "infantry x oracle hero icons 32.bmp"));
      units.add(new UnitEntry(733, "Gaia Forest tree", null, "icon pine tree.bmp"));
      units.add(new UnitEntry(734, "Heka Gigantes", "Heka Gigantes", "special x heka gigantes icons 32.bmp"));
      units.add(new UnitEntry(735, "Tundra Tree", "Tundra Tree", "icon tundra tree icons 32.bmp"));
      units.add(new UnitEntry(736, "Marsh Tree", "Marsh Tree", "icon marsh tree icons 32.bmp"));
      units.add(new UnitEntry(737, "Tartarian Gate", "Tartarian Gate", "god power tartarian gate icons 32.bmp"));
      units.add(new UnitEntry(738, "Oracle Scout", "Oracle (Scout)", "infantry x oracle icons 32.bmp"));
      units.add(new UnitEntry(739, "Tartarian Gate spawn", "Tartarian Spawn", "special x gate spawn icons 32.bmp"));
      units.add(new UnitEntry(740, "Lampades", "Lampades", "special x lampades icons 32.bmp"));
      units.add(new UnitEntry(741, "Kastor Adult", "Kastor (Hero)", "scenario x kastor icons 32.bmp"));
      units.add(new UnitEntry(742, "Marsh Tree Burning", "Marsh Tree Burning", "icon marsh tree icons 32.bmp"));
      units.add(new UnitEntry(743, "Tundra Tree Burning", "Tundra Tree Burning", "icon tundra tree icons 32.bmp"));
      units.add(new UnitEntry(744, "Phoenix From Egg", "Phoenix", "special e phoenix icon.bmp"));
      units.add(new UnitEntry(745, "Hesperides Tree", "Hesperides Tree", "god power hesperides icons 32.bmp"));
      units.add(new UnitEntry(746, "Dryad", "Dryad", "god power dryad icons 32.bmp"));
      units.add(new UnitEntry(747, "Nereid", "Nereid", "special x nereid icons 32.bmp"));
      units.add(new UnitEntry(748, "Titan Gate", "Titan Gate", "improvement secrets of the titans icons 32.bmp"));
      units.add(new UnitEntry(749, "Walking Woods Marsh", "Walking Marsh", "god power walking woods icon.bmp"));
      units.add(new UnitEntry(750, "Walking Woods Tundra", "Walking Tamarack", "god power walking woods icon.bmp"));
      units.add(new UnitEntry(751, "Titan Prometheus", "Prometheus", "special a titan promethean icon 64.bmp"));
      units.add(new UnitEntry(752, "General Melagius", "General Melagius", "scenario x general icons 32.bmp"));
      units.add(new UnitEntry(753, "Pharaoh of Osiris XP", "Son of Osiris (Hero)", "special e son of osiris icon.bmp"));
      units.add(new UnitEntry(754, "Guardian Sleeping XP", "Guardian", "scenario sleeping guardian icon 64.bmp"));
      units.add(new UnitEntry(755, "Statue of Automaton", "Automaton Statue", "special x automaton icons 32.bmp"));
      units.add(new UnitEntry(756, "Statue of Automaton Base", "Automaton Base", "special x automaton icons 32.bmp"));
      units.add(new UnitEntry(757, "Argus", "Argus", "special x argus icons 32.bmp"));
      units.add(new UnitEntry(758, "Gaia Pool", "Gaia Pool", "scenario x gaia pool icons 32.bmp"));
      units.add(new UnitEntry(759, "Spider Egg", "Spider egg", "god power spider eggs icons 64.bmp"));
      units.add(new UnitEntry(760, "King Folstag", "King Folstag", "scenario x folstag icons 32.bmp"));
      units.add(new UnitEntry(761, "Odins Tower", "Tower of Odin", "icon building wonder.bmp"));
      units.add(new UnitEntry(762, "Statue Manticore", "Manticore Statue", "scenario x statue manticore icons.bmp"));
      units.add(new UnitEntry(763, "Statue Cyclops", "Cyclops Statue", "scenario x statue cyclops icons.bmp"));
      units.add(new UnitEntry(764, "Statue Nemean Lion", "Nemean Lion Statue", "scenario x statue nemean lion icons.bmp"));
      units.add(new UnitEntry(765, "Statue Valkyrie", "Valkyrie Statue", "scenario x statue valkyrie icons.bmp"));
      units.add(new UnitEntry(766, "Statue Hydra", "Hydra Statue", "scenario x statue hydra icons.bmp"));
      units.add(new UnitEntry(767, "Statue Chimera", "Chimera Statue", "scenario x statue chimera icons.bmp"));
      units.add(new UnitEntry(768, "Gaia Forest tree burning", "Pine Burning", "icon pine tree.bmp"));
      units.add(new UnitEntry(769, "Tartarian Gate placement", "Tartarian Gate", "god power tartarian gate icons 32.bmp"));
      units.add(new UnitEntry(770, "Tartarian Gate birth", "Tartarian Gate", "god power tartarian gate icons 32.bmp"));
      units.add(new UnitEntry(771, "Krios", "Krios", "scenario theocrat icon 64.bmp"));
      units.add(new UnitEntry(772, "Kronny", "Servant of Kronos", "scenario x kronny icons 32.bmp"));
      units.add(new UnitEntry(773, "Ajax Older", "Ajax (Hero)", "hero g ajax.bmp"));
      units.add(new UnitEntry(774, "Amanra Older", "Queen Amanra (Hero)", "special e amanra icon.bmp"));
      units.add(new UnitEntry(775, "Titan Gate Dead", "Titan Gate Dead", "improvement secrets of the titans icons 64.bmp"));
      units.add(new UnitEntry(776, "Temple Kronos", "Temple of Kronos", "icon building temple.bmp"));
      units.add(new UnitEntry(777, "Arkantos God", "Arkantos (god)", "special g arkantos icon.bmp"));
      units.add(new UnitEntry(778, "Earth", "Earth", "scenario hades gate icon 64.bmp"));
      units.add(new UnitEntry(779, "Kronny Flying", "Servant of Kronos", "scenario x kronny icons 32.bmp"));
      units.add(new UnitEntry(780, "Victory Marker", "Victory Marker", NO_ICON));
      units.add(new UnitEntry(781, "Invisible Wall", "Invisible Wall", "improvement stone wall icon.bmp"));
      units.add(new UnitEntry(782, "Invisible Target", "Invisible Target", "improvement stone wall icon.bmp"));
      units.add(new UnitEntry(783, "Pyramid Osiris Xpack", "Osiris Pyramid", "building osiris pyramid icon 64.bmp"));
      units.add(new UnitEntry(784, "Statue of Melagius", "Statue of Melagius", "scenario x statue general icons.bmp"));
      units.add(new UnitEntry(785, "Temple Overgrown", "Overgrown Temple", "icon building temple.bmp"));
      units.add(new UnitEntry(786, "Roc Tent", "Roc Tent", "world tent icon 64.bmp"));
      units.add(new UnitEntry(787, "Guardian XP", "Guardian", "scenario sleeping guardian icon 64.bmp"));
      units.add(new UnitEntry(788, "Automaton SPC", "Automaton", "special x automaton icons 32.bmp"));
      units.add(new UnitEntry(789, "Summoning Tree", "Summoning Tree Bad", "scenario x summoning tree icons.bmp"));
      units.add(new UnitEntry(790, "Summoning Tree 2", "Summoning Tree", "scenario x summoning tree icons.bmp"));
      units.add(new UnitEntry(791, "Bolder Rolling Small", "Boulder", "scenario boulder wall icon 64.bmp"));
      units.add(new UnitEntry(792, "Tree Finale", "Beautiful Tree", "scenario tamarisk tree icon 64.bmp"));
      units.add(new UnitEntry(793, "Kastor Staff", "Kastor (Hero)", "scenario x kastor icons 32.bmp"));
      units.add(new UnitEntry(794, "Hades Door Small", "Hades Gate", "scenario hades gate icon 64.bmp"));
      units.add(new UnitEntry(795, "Titan Kronos", "Kronos", "scenario x titan kronos icons 32.bmp"));
      units.add(new UnitEntry(796, "Titan Gaia", "Gaia", "special x titan gaia icons 32.bmp"));
      units.add(new UnitEntry(797, "Wolf Arctic", "Arctic Wolf", "animal wolf icon.bmp"));
      units.add(new UnitEntry(798, "Shade XP", "Shade of Olympus", "special g shade icon.bmp"));
      units.add(new UnitEntry(799, "Wolf Arctic 2", "Arctic Wolf", "animal wolf icon.bmp"));
      units.add(new UnitEntry(800, "Bella", "Bella", "bella 32.bmp"));
      units.add(new UnitEntry(801, "Alfred", null, "alfred icon 64.bmp"));
      units.add(new UnitEntry(802, "Ulfsark Starting", "Ulfsark", "infantry n ulfsark icon.bmp"));
      units.add(new UnitEntry(803, "Ram", null, "animal ram icon 64.bmp"));
      units.add(new UnitEntry(804, "Eagle", null, "world hawk icon 64.bmp"));
      units.add(new UnitEntry(805, "Cypress", null, "icon pine tree.bmp"));
      units.add(new UnitEntry(806, "Fish - Herring", null, "animal fish icon.bmp"));
      units.add(new UnitEntry(807, "Villager Chinese", null, "villager c male icon.bmp"));
      units.add(new UnitEntry(808, "Villager Chinese Dead Replacement", null, NO_ICON));
      units.add(new UnitEntry(809, "Bamboo Tree", null, "icon bamboo tree.bmp"));
      units.add(new UnitEntry(810, "Bamboo Tree Burning", null, "icon bamboo tree.bmp"));
      units.add(new UnitEntry(811, "Bamboo stump", null, NO_ICON));
      units.add(new UnitEntry(812, "Panda Bear", null, "animal panda bear icon.bmp"));
      units.add(new UnitEntry(813, "Storage Pit", null, "building storage pit icon.bmp"));
      units.add(new UnitEntry(814, "Barracks Chinese", null, "icon building barracks.bmp"));
      units.add(new UnitEntry(815, "Stable Chinese", null, "icon building stable.bmp"));
      units.add(new UnitEntry(816, "Garden", null, "building garden icon.bmp"));
      units.add(new UnitEntry(817, "Scout Chinese", null, "cavalry c scout icon.bmp"));
      units.add(new UnitEntry(818, "Halberdier", null, "infantry c halberdier icon.bmp"));
      units.add(new UnitEntry(819, "Chu Ko Nu", null, "archer c chu ko nu icon.bmp"));
      units.add(new UnitEntry(820, "Lizard", null, "animal lizard icon.bmp"));
      units.add(new UnitEntry(821, "Yak", null, "animal yak icon.bmp"));
      units.add(new UnitEntry(822, "Tiger", null, "animal tiger icon.bmp"));
      units.add(new UnitEntry(823, "Mounted Archer", null, "archer c mounted archer icon.bmp"));
      units.add(new UnitEntry(824, "Cataphract Chinese", null, "cavalry c cataphract icon.bmp"));
      units.add(new UnitEntry(825, "War Chariot", null, "cavalry c war chariot icon.bmp"));
      units.add(new UnitEntry(826, "Fire Lance", null, "siege c fire lance icon.bmp"));
      units.add(new UnitEntry(827, "Castle", null, "building chinese fortress icon.bmp"));
      units.add(new UnitEntry(828, "Sitting Tiger", null, "siege c sitting tiger icon.bmp"));
      units.add(new UnitEntry(829, "Hero Chinese General", null, "hero c general icon.bmp"));
      units.add(new UnitEntry(830, "Hero Chinese Immortal", null, "hero c immortal icon.bmp"));
      units.add(new UnitEntry(831, "Hero Chinese Monk", null, "hero c monk icon.bmp"));
      units.add(new UnitEntry(832, "Fishing Ship Chinese", null, "boat c fishing boat icon.bmp"));
      units.add(new UnitEntry(833, "Junk", null, "boat c junk icon.bmp"));
      units.add(new UnitEntry(834, "Fire Ship Chinese", null, "boat c fire ship chinese icon.bmp"));
      units.add(new UnitEntry(835, "Siege Ship Chinese", null, "boat c siege ship chinese icon.bmp"));
      units.add(new UnitEntry(836, "Transport Ship Chinese", null, "boat c transport icon.bmp"));
      units.add(new UnitEntry(837, "Caravan Chinese", null, "trade c caravan icon.bmp"));
      units.add(new UnitEntry(838, "UI Range Indicator Chinese SFX", null, NO_ICON));
      units.add(new UnitEntry(839, "Jungle Tree", null, "icon palm tree.bmp"));
      units.add(new UnitEntry(840, "Jungle Tree Burning", null, "icon palm tree.bmp"));
      units.add(new UnitEntry(841, "Jungle Tree Stump", null, NO_ICON));
      units.add(new UnitEntry(842, "Qilin", null, "special c qilin icon.bmp"));
      units.add(new UnitEntry(843, "Terracotta Soldier", null, "special c terracotta soldier icon.bmp"));
      units.add(new UnitEntry(844, "Terracotta Soldier Dead Replacement", null, NO_ICON));
      units.add(new UnitEntry(845, "Monkey King", null, "special c monkey king icon.bmp"));
      units.add(new UnitEntry(846, "War Salamander", null, "special c war salamander icon.bmp"));
      units.add(new UnitEntry(847, "Pixiu", null, "special c pixiu icon.bmp"));
      units.add(new UnitEntry(848, "Jiangshi", null, "special c jiangshi icon.bmp"));
      units.add(new UnitEntry(849, "Azure Dragon", null, "special c azure dragon icon.bmp"));
      units.add(new UnitEntry(850, "Vermilion Bird", null, "special c vermilion bird icon.bmp"));
      units.add(new UnitEntry(851, "White Tiger", null, "special c white tiger icon.bmp"));
      units.add(new UnitEntry(852, "Dragon Turtle", null, "special c dragon turtle icon.bmp"));
      units.add(new UnitEntry(853, "Griffon", null, "special g griffon icon.bmp"));
      units.add(new UnitEntry(854, "Apep", null, NO_ICON));
      units.add(new UnitEntry(855, "Bondi", null, "infantry n bondi icon.bmp"));
      units.add(new UnitEntry(856, "Pirate Ship Norse", "Pirate Ship", "scenario n pirate ship icon 64.bmp"));
      units.add(new UnitEntry(857, "Bush Short", null, NO_ICON));
      units.add(new UnitEntry(858, "William Walrus", null, "special g god statue icon 64.bmp"));
      units.add(new UnitEntry(859, "Golem", null, "special g minotaur icon.bmp"));
      units.add(new UnitEntry(860, "Trollkarien", null, "special g cyclops icon.bmp"));
      units.add(new UnitEntry(861, "Vulture Scout", null, "special e vulture icon.bmp"));
      units.add(new UnitEntry(862, "Harpy Scout", null, "special e vulture icon.bmp"));
      units.add(new UnitEntry(863, "Rock Dirt Sprite", null, NO_ICON));
      units.add(new UnitEntry(864, "Rock Dirt Small", null, NO_ICON));
      units.add(new UnitEntry(865, "Rock Dirt Big", null, NO_ICON));
      units.add(new UnitEntry(866, "Rock Overgrown Sprite", null, NO_ICON));
      units.add(new UnitEntry(867, "Rock Overgrown Small", null, NO_ICON));
      units.add(new UnitEntry(868, "Rock Overgrown Big", null, NO_ICON));
      units.add(new UnitEntry(869, "Jade Mine", null, "icon gold mine 64.bmp"));
      units.add(new UnitEntry(870, "Jade Mine Small", null, "icon gold mine 64.bmp"));
      units.add(new UnitEntry(871, "Jade Mine Tiny", null, "icon gold mine 64.bmp"));
      units.add(new UnitEntry(872, "Ball of Fire Vermilion Bird", null, NO_ICON));
      units.add(new UnitEntry(873, "Tornado Vermilion Bird", null, NO_ICON));
      units.add(new UnitEntry(874, "Parrot", null, "world hawk icon 64.bmp"));
      units.add(new UnitEntry(875, "Elephant Indian", null, "animal elephant icon.bmp"));
      units.add(new UnitEntry(876, "Duck", null, "animal duck icon.bmp"));
      units.add(new UnitEntry(877, "Dog", null, "animal wolf icon.bmp"));
      units.add(new UnitEntry(878, "Earth Dragon", null, "special c earth dragon icon.bmp"));
      units.add(new UnitEntry(879, "Barrage", null, NO_ICON));
      units.add(new UnitEntry(880, "Goat Chinese", "Goat", "animal goat icon.bmp"));
      units.add(new UnitEntry(881, "Jialong", null, "scenario c jiaolong icon.bmp"));
      units.add(new UnitEntry(882, "Shun", null, "scenario c shun icon.bmp"));
      units.add(new UnitEntry(883, "Flood", null, NO_ICON));
      units.add(new UnitEntry(884, "Regent", null, "special g god statue icon 64.bmp"));
      units.add(new UnitEntry(885, "Jungle Palm", null, "icon palm tree.bmp"));
      units.add(new UnitEntry(886, "Jungle Palm Burning", null, "icon palm tree.bmp"));
      units.add(new UnitEntry(887, "Jungle Palm Stump", null, NO_ICON));
      units.add(new UnitEntry(888, "Dam", null, "icon building mining camp.bmp"));
      units.add(new UnitEntry(889, "Zhi", null, "scenario c zhi icon.bmp"));
      units.add(new UnitEntry(890, "Danzhu", null, "scenario c danzhu icon.bmp"));
      units.add(new UnitEntry(891, "Destruction 1x1 SPC", "Destruction 1x1", NO_ICON));
      units.add(new UnitEntry(892, "Destruction 2x2 SPC", "Destruction 2x2", NO_ICON));
      units.add(new UnitEntry(893, "Destruction 3x3 SPC", "Destruction 3x3", NO_ICON));
      units.add(new UnitEntry(894, "Destruction 4x4 SPC", "Destruction 4x4", NO_ICON));
      units.add(new UnitEntry(895, "Destruction 5x5 SPC", "Destruction 5x5", NO_ICON));
      units.add(new UnitEntry(896, "Destruction 8x8 SPC", "Destruction 8x8", NO_ICON));
      units.add(new UnitEntry(897, "Earth Dragon Hole", null, NO_ICON));
      units.add(new UnitEntry(898, "Kraken SPC2", null, "special n kraken icon.bmp"));
      units.add(new UnitEntry(899, "Geyser", null, NO_ICON));
      units.add(new UnitEntry(900, "Uproot 1x1", null, "god power uproot icon.bmp"));
      units.add(new UnitEntry(901, "Uproot 2x2", null, "god power uproot icon.bmp"));
      units.add(new UnitEntry(902, "Uproot 3x3", null, "god power uproot icon.bmp"));
      units.add(new UnitEntry(903, "Uproot 4x4", null, "god power uproot icon.bmp"));
      units.add(new UnitEntry(904, "Uproot 5x5", null, "god power uproot icon.bmp"));
      units.add(new UnitEntry(905, "Uproot 6x6", null, "god power uproot icon.bmp"));
      units.add(new UnitEntry(906, "Uproot 7x7", null, "god power uproot icon.bmp"));
      units.add(new UnitEntry(907, "Uproot 8x8", null, "god power uproot icon.bmp"));
      units.add(new UnitEntry(908, "Inferno Field", null, NO_ICON));
      units.add(new UnitEntry(909, "Bolder Wall Asian", "Boulder Wall", "scenario boulder wall icon 64.bmp"));
      units.add(new UnitEntry(910, "Physician", null, "hero g physician icon.bmp"));
      units.add(new UnitEntry(911, "Bogsveigir", null, "archer n bogsveigir icon.bmp"));
      units.add(new UnitEntry(912, "Khopesh", null, "infantry e khopesh icon.bmp"));
      units.add(new UnitEntry(913, "Onager", null, "siege x onager icon.bmp"));
      units.add(new UnitEntry(914, "Fire Lance Projectile", null, NO_ICON));
      units.add(new UnitEntry(915, "Tsunami", null, NO_ICON));
      units.add(new UnitEntry(916, "Emperor", null, "special g god statue icon 64.bmp"));
      units.add(new UnitEntry(917, "Lazer Panda", null, "animal bear icon.bmp"));
      units.add(new UnitEntry(918, "Tsunami Range Indicator", null, NO_ICON));
      units.add(new UnitEntry(919, "Big Splash", null, NO_ICON));
      units.add(new UnitEntry(920, "Timberharvest", null, NO_ICON));
      units.add(new UnitEntry(921, "Imperial Examination", null, NO_ICON));
      units.add(new UnitEntry(922, "Blessed Construction", null, NO_ICON));
      units.add(new UnitEntry(923, "Recreation", null, NO_ICON));
      units.add(new UnitEntry(924, "Sitting Tiger Shennong", null, "siege c sitting tiger icon.bmp"));
      units.add(new UnitEntry(925, "Qilin Heal", null, NO_ICON));
      units.add(new UnitEntry(926, "Fire Lance Shennong", null, "siege c fire lance icon.bmp"));
      units.add(new UnitEntry(927, "Servant Chinese", null, "hero c immortal icon.bmp"));
      units.add(new UnitEntry(928, "Ao Kuang", null, "special c azure dragon icon.bmp"));
      units.add(new UnitEntry(929, "Walking Woods Jungle Tree", "Walking Woods", "god power walking woods icon.bmp"));
      units.add(new UnitEntry(930, "Walking Woods Jungle Palm", "Walking Palm", "god power walking woods icon.bmp"));
      units.add(new UnitEntry(931, "Walking Woods Bamboo", "Walking Woods", "god power walking woods icon.bmp"));
      units.add(new UnitEntry(932, "Snowman", null, NO_ICON));
      units.add(new UnitEntry(933, "Santa", null, "special n mountain giant icon.bmp"));
      units.add(new UnitEntry(934, "Reindeer", null, "animal elk icon.bmp"));
   }
   
   public List<UnitEntry> getUnits() {
      return units;
   }
   
}
