//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.06 at 05:05:27 PM GMT 
//


package model.xml;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="method" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="parameters" type="{}parameter"/>
 *                   &lt;/sequence>
 *                   &lt;sequence minOccurs="0">
 *                     &lt;element name="javadoc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/sequence>
 *                 &lt;/sequence>
 *                 &lt;attribute name="return" use="required" type="{}type" />
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "method"
})
@XmlRootElement(name = "model")
public class Model {

    @XmlElement(required = true)
    protected List<Model.Method> method;

    /**
     * Gets the value of the method property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the method property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Model.Method }
     * 
     * 
     */
    public List<Model.Method> getMethod() {
        if (method == null) {
            method = new ArrayList<Model.Method>();
        }
        return this.method;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="parameters" type="{}parameter"/>
     *         &lt;/sequence>
     *         &lt;sequence minOccurs="0">
     *           &lt;element name="javadoc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;/sequence>
     *       &lt;/sequence>
     *       &lt;attribute name="return" use="required" type="{}type" />
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameters",
        "javadoc"
    })
    public static class Method {

        protected List<Parameter> parameters;
        protected String javadoc;
        @XmlAttribute(name = "return", required = true)
        protected Type _return;
        @XmlAttribute(name = "name", required = true)
        protected String name;

        /**
         * Gets the value of the parameters property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameters property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameters().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Parameter }
         * 
         * 
         */
        public List<Parameter> getParameters() {
            if (parameters == null) {
                parameters = new ArrayList<Parameter>();
            }
            return this.parameters;
        }

        /**
         * Gets the value of the javadoc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getJavadoc() {
            return javadoc;
        }

        /**
         * Sets the value of the javadoc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setJavadoc(String value) {
            this.javadoc = value;
        }

        /**
         * Gets the value of the return property.
         * 
         * @return
         *     possible object is
         *     {@link Type }
         *     
         */
        public Type getReturn() {
            return _return;
        }

        /**
         * Sets the value of the return property.
         * 
         * @param value
         *     allowed object is
         *     {@link Type }
         *     
         */
        public void setReturn(Type value) {
            this._return = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

    }

}
